USE liveart;

INSERT INTO [dbo].[Address] VALUES ('535 Anndale Court','Waterloo',1,'N2K 2E1');
INSERT INTO [dbo].[Address] VALUES ('750 Balsam Avenue','Penticton',6,'V2A 3J1');
INSERT INTO [dbo].[Address] VALUES ('572 Cawston Avenue','Kelowna',6,'V1Y 6Z2');
INSERT INTO [dbo].[Address] VALUES ('32 Amy Close','Red Deer',9,'T4R 3H3');
INSERT INTO [dbo].[Address] VALUES ('44 Catherine Fraser Street','North Glengarry',1,'K0C 1A0');
INSERT INTO [dbo].[Address] VALUES ('67 Brembel Street','Kitchener',1,'N2B 3N1');
INSERT INTO [dbo].[Address] VALUES ('34 Blanchard Crescent','Essa',1,'L0M 1B0');
INSERT INTO [dbo].[Address] VALUES ('60 Chebogue Lane','Dartmouth',3,'B2W 0B9');
INSERT INTO [dbo].[Address] VALUES ('86 Boyd Street','Champlain',1,'K0B 1R0');
INSERT INTO [dbo].[Address] VALUES ('565 Colyer Street','Brock',1,'L0K 1A0');
INSERT INTO [dbo].[Address] VALUES ('555 Wissler Road','Waterloo',1,'N2K 4A2');
INSERT INTO [dbo].[Address] VALUES ('245 Alfred Paterson Drive','Markham',1,'L6E 2G1');
INSERT INTO [dbo].[Address] VALUES ('450 Cadder Avenue','Kelowna',6,'V1Y 1T5');
INSERT INTO [dbo].[Address] VALUES ('415 Butchart Drive NW','Edmonton',9,'T6R 2L4');
INSERT INTO [dbo].[Address] VALUES ('55 Bellbrook Crescent','Dartmouth',3,'B2W 6S1');
INSERT INTO [dbo].[Address] VALUES ('114 Clifton Road','Kelowna',6,'V1Y 8K9');
INSERT INTO [dbo].[Address] VALUES ('102 Compton Road','Regina',8,'S4S 6B4');
INSERT INTO [dbo].[Address] VALUES ('671 Cape Avenue','Burlington',1,'L7L 4M5');
INSERT INTO [dbo].[Address] VALUES ('13 Balcomes Drive','Halifax',3,'B3N 1J4');
INSERT INTO [dbo].[Address] VALUES ('728 Bowlsby Place','Victoria',6,'V9A 2V8');
INSERT INTO [dbo].[Address] VALUES ('25 Clematis Court Southeast','Medicine Hat',9,'T1B 2A4');
INSERT INTO [dbo].[Address] VALUES ('43 Avon Road','Kitchener',1,'N2B 3C4');
INSERT INTO [dbo].[Address] VALUES ('6 Fuller Drive','Guelph',1,'N1E 7C4');
INSERT INTO [dbo].[Address] VALUES ('203 Boyko Road','Thunder Bay',1,'P7G 1J1');
INSERT INTO [dbo].[Address] VALUES ('112 Chain Lake Drive','Halifax',3,'B3S 0B7');
INSERT INTO [dbo].[Address] VALUES ('292 Blackman Street','New Westminster',6,'V3L 2W6');
INSERT INTO [dbo].[Address] VALUES ('693 Amesbury Court','Sarnia',1,'N7V 3Z3');
INSERT INTO [dbo].[Address] VALUES ('29 Altura Road','Kelowna',6,'V1Y 8K9');
INSERT INTO [dbo].[Address] VALUES ('392 Blackburn Close SW','Edmonton',9,'T6W 2P6');
INSERT INTO [dbo].[Address] VALUES ('797 Bridges Street','Halifax',3,'B3H 2X9');
INSERT INTO [dbo].[Address] VALUES ('4 Brant-Walkerton','Brockton',1,'N0G 2V0');
INSERT INTO [dbo].[Address] VALUES ('88 Casey Street','Madawaska Valley',1,'K0J 1B0');
INSERT INTO [dbo].[Address] VALUES ('11 Atwell Street','Red Deer',9,'T4R 3H3');
INSERT INTO [dbo].[Address] VALUES ('531 Argyle Avenue North','North Perth',1,'N4W 1L1');
INSERT INTO [dbo].[Address] VALUES ('11 Borlase Crescent','Regina',8,'S4N 4C8');
INSERT INTO [dbo].[Address] VALUES ('9 Birchwood Terrace','Dartmouth',3,'B3A 3W2');
INSERT INTO [dbo].[Address] VALUES ('60 Buckthorn Crescent','Guelph',1,'N1E 7C4');
INSERT INTO [dbo].[Address] VALUES ('162 Church Drive','Regina',8,'S4R 7M2');
INSERT INTO [dbo].[Address] VALUES ('15 Barr Street','Regina',8,'S4R 0P7');
INSERT INTO [dbo].[Address] VALUES ('447 Carrier Place','Prince George',6,'V2M 6Y4');
INSERT INTO [dbo].[Address] VALUES ('147 Bridlepath Trail','Sarnia',1,'N7S 6K2');
INSERT INTO [dbo].[Address] VALUES ('29 Bushey Avenue','Essa',1,'L0M 1B2');
INSERT INTO [dbo].[Address] VALUES ('19 Auburn Bay Lane SE','Calgary',9,'T3M 0A6');
INSERT INTO [dbo].[Address] VALUES ('149 Auchinean Road','Georgian Bluffs',1,'N4K 5N4');
INSERT INTO [dbo].[Address] VALUES ('28 Cardinal Avenue','Red Deer',9,'T4R 1X9');
INSERT INTO [dbo].[Address] VALUES ('791 Cassiar Road','Kelowna',6,'V1X 4J4');
INSERT INTO [dbo].[Address] VALUES ('803 Sunningdale Road','London',1,'N6G 3Y9');
INSERT INTO [dbo].[Address] VALUES ('195 Colonel Nicholson Lane','Ottawa',1,'K0A 3M0');
INSERT INTO [dbo].[Address] VALUES ('15 Centennial Road','Kitchener',1,'N2B 3N1');
INSERT INTO [dbo].[Address] VALUES ('60 Arbour Crest Terrace NW','Calgary',9,'T3G 4L3');
INSERT INTO [dbo].[Address] VALUES ('193 Bestwick Drive','Kamloops',6,'V2C 1N6');
INSERT INTO [dbo].[Address] VALUES ('567 Dufferin Street West','North Dundas',1,'K0C 2K0');
INSERT INTO [dbo].[Address] VALUES ('102 Arbour Crest Circle NW','Calgary',9,'T3G 4H3');
INSERT INTO [dbo].[Address] VALUES ('49 Ann Street South','Brock',1,'L0E 1E0');
INSERT INTO [dbo].[Address] VALUES ('22 Wragge Street E','South Bruce',1,'N0G 2S0');
INSERT INTO [dbo].[Address] VALUES ('4 Henry Street','Ramara',1,'L3V 1P1');
INSERT INTO [dbo].[Address] VALUES ('46 Bridgeview Drive','Halifax',3,'B3P 1M2');
INSERT INTO [dbo].[Address] VALUES ('56 Artemesia Street South','Southgate',1,'N0C 1B0');
INSERT INTO [dbo].[Address] VALUES ('24 Cavan Street','Grey Highlands',1,'N0C 1H0');
INSERT INTO [dbo].[Address] VALUES ('350 Colborne Street South','Brockton',1,'N0G 2V0');
INSERT INTO [dbo].[Address] VALUES ('725 Burton Crescent NW','Edmonton',9,'T6R 2L4');
INSERT INTO [dbo].[Address] VALUES ('439 Audubon Court','Kelowna',6,'V1W 4W4');
INSERT INTO [dbo].[Address] VALUES ('68 Archibald Crescent','Red Deer',9,'T4R 2H3');
INSERT INTO [dbo].[Address] VALUES ('31 Astrid Way','Fredericton',4,'E3B 5Z1');
INSERT INTO [dbo].[Address] VALUES ('166 Claxton Crescent','Prince George',6,'V2M 6Y4');
INSERT INTO [dbo].[Address] VALUES ('93 Bird''s Lane','King',1,'L7B 0C8');
INSERT INTO [dbo].[Address] VALUES ('14 Churchill Court','Dartmouth',3,'B2X 1N9');
INSERT INTO [dbo].[Address] VALUES ('1022 Breckenridge Drive NW','Edmonton',9,'T5T 7C6');
INSERT INTO [dbo].[Address] VALUES ('30 Chism Close','Red Deer',9,'T4R 1X9');
INSERT INTO [dbo].[Address] VALUES ('32 Cecil Crescent','Regina',8,'S4T 1B8');
INSERT INTO [dbo].[Address] VALUES ('156 Arbour Stone Crescent NW','Calgary',9,'T3G 5B3');
INSERT INTO [dbo].[Address] VALUES ('98 Bettenson Street','Red Deer',9,'T4R 1N9');
INSERT INTO [dbo].[Address] VALUES ('15 Barkton Lane','Halifax',3,'B3M 3Y7');
INSERT INTO [dbo].[Address] VALUES ('264 Bessborough Street','Fredericton',4,'E3B 3H2');
INSERT INTO [dbo].[Address] VALUES ('520 Buchanan Road NW','Edmonton',9,'T6R 2L4');
INSERT INTO [dbo].[Address] VALUES ('20 Brecht Street','Brock',1,'L0C 1H0');
INSERT INTO [dbo].[Address] VALUES ('67 McCarthy Crescent','Essa',1,'L0M 1B2');
INSERT INTO [dbo].[Address] VALUES ('451 Sandybrook Drive','London',1,'N6G 3Y9');
INSERT INTO [dbo].[Address] VALUES ('33 Chippewa Road','Sherwood Park',9,'T8A 4W5');
INSERT INTO [dbo].[Address] VALUES ('53 Cobbledick Street','Clarington',1,'L0B 1M0');
INSERT INTO [dbo].[Address] VALUES ('32 Bournemouth Avenue','Kitchener',1,'N2B 1Z9');
INSERT INTO [dbo].[Address] VALUES ('35 Clarke Street','Port Colborne',1,'L3K 1P4');
INSERT INTO [dbo].[Address] VALUES ('565 Butterworth Way NW','Edmonton',9,'T6R 2V4');
INSERT INTO [dbo].[Address] VALUES ('482 Annapolis Court','Waterloo',1,'N2K 4A2');
INSERT INTO [dbo].[Address] VALUES ('109 Burnt Lake Trail','Red Deer',9,'T4S 2W7');
INSERT INTO [dbo].[Address] VALUES ('205 Bancroft Close NW','Edmonton',9,'T5T 1K8');
INSERT INTO [dbo].[Address] VALUES ('8 Calder Bay Southeast','Medicine Hat',9,'T1B 2H2');
INSERT INTO [dbo].[Address] VALUES ('45 Blacksmith Road','Rideau Lakes',1,'K7A 5B8');
INSERT INTO [dbo].[Address] VALUES ('775 County Road 6E','South Bruce',1,'N0G 2J0');
INSERT INTO [dbo].[Address] VALUES ('20 Bobolink Avenue','Toronto',1,'M1X 1W2');
INSERT INTO [dbo].[Address] VALUES ('33 Bemerton Court','Toronto',1,'M1V 4R1');
INSERT INTO [dbo].[Address] VALUES ('92 Anderson Close','Red Deer',9,'T4N 6R9');
INSERT INTO [dbo].[Address] VALUES ('5 Hillcrest Street West','South Bruce',1,'N0G 2S0');
INSERT INTO [dbo].[Address] VALUES ('394 Clements Drive','Fredericton',4,'E3B 5Z1');
INSERT INTO [dbo].[Address] VALUES ('21 Clarewood Drive','Brockton',1,'N0G 2V0');
INSERT INTO [dbo].[Address] VALUES ('503 Carse Lane NW','Edmonton',9,'T6R 0R9');
INSERT INTO [dbo].[Address] VALUES ('343 Arrowstone Drive','Kamloops',6,'V2C 1P9');
INSERT INTO [dbo].[Address] VALUES ('43 Apple Drive','Cambridge',1,'N3C 1B7');
INSERT INTO [dbo].[Address] VALUES ('7 Corcoran Street','Stratford',1,'N5A 2N2');
INSERT INTO [dbo].[Address] VALUES ('10 Corkery Bay','Regina',8,'S4R 7M2');
INSERT INTO [dbo].[Address] VALUES ('11 Cascaden Street','Toronto',1,'M1V 4R1');
INSERT INTO [dbo].[Address] VALUES ('664 Baie-des-Castors Street','Ottawa',1,'K4A 1C2');
INSERT INTO [dbo].[Address] VALUES ('68 Armament Road','Dartmouth',3,'B3A 3A6');
INSERT INTO [dbo].[Address] VALUES ('81 Camden-Sheffield Boundary Road','Stone Mills',1,'K0K 3G0');
INSERT INTO [dbo].[Address] VALUES ('20 Anquetel Close','Red Deer',9,'T4N 6R9');
INSERT INTO [dbo].[Address] VALUES ('303 Brompton Avenue','Woodstock',1,'N4S 5S1');
INSERT INTO [dbo].[Address] VALUES ('39 Auld Bay','Regina',8,'S4R 7M2');
INSERT INTO [dbo].[Address] VALUES ('53 Castle Crescent','Red Deer',9,'T4R 1X9');
INSERT INTO [dbo].[Address] VALUES ('96 B12 Road','Rideau Lakes',1,'K0G 1W0');
INSERT INTO [dbo].[Address] VALUES ('1 Bowling Green','Middlesex Centre',1,'N7G 4J8');
INSERT INTO [dbo].[Address] VALUES ('118 Brookside Drive','Fredericton',4,'E3A 1B8');
INSERT INTO [dbo].[Address] VALUES ('725 Campbell Street','Huron-Kinloss',1,'N0G 2H0');
INSERT INTO [dbo].[Address] VALUES ('18 Rideau Lane','North Grenville',1,'K0G 1J0');
INSERT INTO [dbo].[Address] VALUES ('770 Angler Way','Waterloo',1,'N2K 4L7');
INSERT INTO [dbo].[Address] VALUES ('726 Barrie Close SW','Edmonton',9,'T6W 1S4');
INSERT INTO [dbo].[Address] VALUES ('644 Lake Trail Drive','Windsor',1,'N9G 1X3');
INSERT INTO [dbo].[Address] VALUES ('44 Caliper Road','Brampton',1,'L6P 3X3');
INSERT INTO [dbo].[Address] VALUES ('458 Colonial Crescent','Peterborough',1,'K9L 1M9');
INSERT INTO [dbo].[Address] VALUES ('50 Brown Avenue','Dartmouth',3,'B3B 1X8');
INSERT INTO [dbo].[Address] VALUES ('76 Cameron Court','Fredericton',4,'E3B 9R6');
INSERT INTO [dbo].[Address] VALUES ('16 Ash Close','Red Deer',9,'T4R 2H3');
INSERT INTO [dbo].[Address] VALUES ('53 Blackwood Bay','Winnipeg',5,'R3T 5S7');
INSERT INTO [dbo].[Address] VALUES ('362 Brookview Drive','Regina',8,'S4R 7M2');
INSERT INTO [dbo].[Address] VALUES ('509 Wheatley Drive','Sarnia',1,'N7S 6K2');
INSERT INTO [dbo].[Address] VALUES ('355 Blackwood Crescent SW','Edmonton',9,'T6W 2P6');
INSERT INTO [dbo].[Address] VALUES ('258 Avonlea Way','Kelowna',6,'V1Y 8K9');
INSERT INTO [dbo].[Address] VALUES ('13 Bluebell Court Southeast','Medicine Hat',9,'T1B 2L2');
INSERT INTO [dbo].[Address] VALUES ('324 Beringer Crescent NW','Edmonton',9,'T5T 1K8');
INSERT INTO [dbo].[Address] VALUES ('118 Colwell Drive','Fredericton',4,'E3A 6R1');
INSERT INTO [dbo].[Address] VALUES ('59 County Road 17','Stone Mills',1,'K0K 2S0');
INSERT INTO [dbo].[Address] VALUES ('509 Cherry Blossom Court','Sarnia',1,'N7S 6K2');
INSERT INTO [dbo].[Address] VALUES ('49 Calderwood Bay','Winnipeg',5,'R3T 6A5');
INSERT INTO [dbo].[Address] VALUES ('163 Arbour Gen Close NW','Calgary',9,'T3G 3Y8');
INSERT INTO [dbo].[Address] VALUES ('35 Cavan Street','Grey Highlands',1,'N0C 1H0');
INSERT INTO [dbo].[Address] VALUES ('10 Cassell Lane','Rideau Lakes',1,'K7A 3Z3');
INSERT INTO [dbo].[Address] VALUES ('56 Auburn Glen Gardens SE','Calgary',9,'T2Z 1E5');
INSERT INTO [dbo].[Address] VALUES ('76 Carswell Avenue','Oshawa',1,'L1G 4X8');
INSERT INTO [dbo].[Address] VALUES ('664 Armour Crescent','Kelowna',6,'V1W 1A3');
INSERT INTO [dbo].[Address] VALUES ('7 Berwick Crescent','Essa',1,'L0M 1B2');
INSERT INTO [dbo].[Address] VALUES ('245 Cornett Drive','Red Deer',9,'T4R 1X9');
INSERT INTO [dbo].[Address] VALUES ('11 Clover Court Southeast','Medicine Hat',9,'T1B 2G8');
INSERT INTO [dbo].[Address] VALUES ('25 Bamberg Court','Fredericton',4,'E3A 1B8');
INSERT INTO [dbo].[Address] VALUES ('18 Cityview Drive South','Guelph',1,'N1E 7H1');
INSERT INTO [dbo].[Address] VALUES ('178 Cambie Place','Penticton',6,'V2A 1H4');
INSERT INTO [dbo].[Address] VALUES ('377 Bolean Place','Kamloops',6,'V2H 1M3');
INSERT INTO [dbo].[Address] VALUES ('187 Citadel Meadow Close NW','Calgary',9,'T3G 4T4');
INSERT INTO [dbo].[Address] VALUES ('13 Citadel Crest Place NW','Calgary',9,'T3G 4N1');
INSERT INTO [dbo].[Address] VALUES ('600 Bissette Road','Kamloops',6,'V2B 8R8');
INSERT INTO [dbo].[Address] VALUES ('79 Brookview Place','Brockville',1,'K6V 4N5');
INSERT INTO [dbo].[Address] VALUES ('605 Expo Boulevard','Vancouver',6,'V6B 1V4');
INSERT INTO [dbo].[Address] VALUES ('203 Byrne Place SW','Edmonton',9,'T6W 1S4');
INSERT INTO [dbo].[Address] VALUES ('23 Berkley Avenue','Port Colborne',1,'L3K 1S4');
INSERT INTO [dbo].[Address] VALUES ('20 Boathouse Lane','Dartmouth',3,'B3A 2L3');
INSERT INTO [dbo].[Address] VALUES ('60 Baybarry Street','Fredericton',4,'E3C 2B8');
INSERT INTO [dbo].[Address] VALUES ('150 Castle Drive NW','Edmonton',9,'T5X 4X4');
INSERT INTO [dbo].[Address] VALUES ('16 Bethel Avenue','Dartmouth',3,'B3A 4E4');
INSERT INTO [dbo].[Address] VALUES ('563 Burnside Road East','Victoria',6,'V8T 4N4');
INSERT INTO [dbo].[Address] VALUES ('42 Carlisle Road','Hamilton',1,'L8N 2Z7');
INSERT INTO [dbo].[Address] VALUES ('80 Alton Towers Circle','Toronto',1,'M1V 4L3');
INSERT INTO [dbo].[Address] VALUES ('251 Bardis Drive','Laurentian Valley',1,'K8A 7R5');
INSERT INTO [dbo].[Address] VALUES ('80 Caverly Lane','Marmora and Lake',1,'K0K 2M0');
INSERT INTO [dbo].[Address] VALUES ('555 Nechako Avenue','Courtenay',6,'V9N 0A6');
INSERT INTO [dbo].[Address] VALUES ('28 Beachaven Drive','St. Catharines',1,'L2M 7C4');
INSERT INTO [dbo].[Address] VALUES ('52 Artemesia Street North','Southgate',1,'N0C 1B0');
INSERT INTO [dbo].[Address] VALUES ('793 Comstock Crescent','Brockville',1,'K6V 6H9');
INSERT INTO [dbo].[Address] VALUES ('335 Chino Place','Kamloops',6,'V2E 2R2');
INSERT INTO [dbo].[Address] VALUES ('399 Barrett Drive','Red Deer',9,'T4R 1N9');
INSERT INTO [dbo].[Address] VALUES ('51 Andrews Crescent','Regina',8,'S4R 8C5');
INSERT INTO [dbo].[Address] VALUES ('20 Amberwood Lane','Fredericton',4,'E3C 2B8');
INSERT INTO [dbo].[Address] VALUES ('83 Amanda Walk','Cambridge',1,'N1T 2K8');
INSERT INTO [dbo].[Address] VALUES ('52 Compton Street','Kingston',1,'K7K 2S7');
INSERT INTO [dbo].[Address] VALUES ('368 Chambers Place','London',1,'N6G 3Y9');
INSERT INTO [dbo].[Address] VALUES ('161 Chur Lee Road','Whitestone',1,'P0A 1G0');
INSERT INTO [dbo].[Address] VALUES ('17 Armshore Drive','Halifax',3,'B3L 1N5');
INSERT INTO [dbo].[Address] VALUES ('75 Chelton Woods Lane','Halifax',3,'B3M 3W8');
INSERT INTO [dbo].[Address] VALUES ('354 Bentinck Street','St. Clair',1,'N0N 1G0');
INSERT INTO [dbo].[Address] VALUES ('10 Atter Close','Red Deer',9,'T4R 2H3');
INSERT INTO [dbo].[Address] VALUES ('30 Bacchus Island Road','Rideau Lakes',1,'K7A 4S4');
INSERT INTO [dbo].[Address] VALUES ('657 Bermer Place','Kamloops',6,'V2B 6L1');
INSERT INTO [dbo].[Address] VALUES ('286 Cavendish Street','Regina',8,'S4N 4C8');
INSERT INTO [dbo].[Address] VALUES ('123 Blackwell Crescent','Oshawa',1,'L1H 7K4');
INSERT INTO [dbo].[Address] VALUES ('785 Barrie Drive','Kamloops',6,'V2B 3Y1');
INSERT INTO [dbo].[Address] VALUES ('136 Steffen Road','Perth South',1,'N0K 1X0');
INSERT INTO [dbo].[Address] VALUES ('20 Butterworth Point NW','Edmonton',9,'T6R 2V4');
INSERT INTO [dbo].[Address] VALUES ('41 Centreview Street','Clarington',1,'L0B 1M0');
INSERT INTO [dbo].[Address] VALUES ('240 Cherrywood Avenue','Pickering',1,'L1V 3Y9');
INSERT INTO [dbo].[Address] VALUES ('170 Centennial Drive','Courtenay',6,'V9N 1G0');
INSERT INTO [dbo].[Address] VALUES ('42 Argus Drive','Dartmouth',3,'B3A 4Y1');
INSERT INTO [dbo].[Address] VALUES ('21 Cloverhaven Road','Brampton',1,'L6P 0A2');
INSERT INTO [dbo].[Address] VALUES ('21 Castlewood Avenue','King',1,'L0G 1T0');
INSERT INTO [dbo].[Address] VALUES ('48 Carmel Road','Quinte West',1,'K0K 3E0');
INSERT INTO [dbo].[Address] VALUES ('7 Cedar Street','Brock',1,'L0C 1H0');
INSERT INTO [dbo].[Address] VALUES ('62 Brookshire Court','Bedford',3,'B4A 3P1');
INSERT INTO [dbo].[Address] VALUES ('331 Balsa Street','Fredericton',4,'E3A 3M8');
INSERT INTO [dbo].[Address] VALUES ('140 Coburn Court','Fredericton',4,'E3B 5Z1');
INSERT INTO [dbo].[Address] VALUES ('487 Buchanan Road NW','Edmonton',9,'T6R 2L4');
INSERT INTO [dbo].[Address] VALUES ('177 Comazzetto Road','Kamloops',6,'V2C 3Z5');
INSERT INTO [dbo].[Address] VALUES ('627 Ardleigh Crescent','Burlington',1,'L7L 3V7');
INSERT INTO [dbo].[Address] VALUES ('710 Highway 33','Kelowna',6,'V1X 2M9');
INSERT INTO [dbo].[Address] VALUES ('696 Cathcart Boulevard','Sarnia',1,'N7V 3Z3');

INSERT INTO [dbo].[User] VALUES (1,'Erlinda_Ryberg_71@hotmail.com','ErlindaRyberg','Erlinda','Ryberg','8/16/1988');
INSERT INTO [dbo].[User] VALUES (2,'Rosetta_Haswell_40@hotmail.com','RosettaHaswell','Rosetta','Haswell','12/1/1975');
INSERT INTO [dbo].[User] VALUES (3,'Alec_Ferringo_45@hotmail.com','AlecFerringo','Alec','Ferringo','2/11/1978');
INSERT INTO [dbo].[User] VALUES (4,'Yan_Ringuette_92@hotmail.com','YanRinguette','Yan','Ringuette','11/12/1996');
INSERT INTO [dbo].[User] VALUES (5,'Alycia_Nevins_87@hotmail.com','AlyciaNevins','Alycia','Nevins','2/20/1995');
INSERT INTO [dbo].[User] VALUES (6,'Lakita_Pennebaker_38@hotmail.com','LakitaPennebaker','Lakita','Pennebaker','1/17/1975');
INSERT INTO [dbo].[User] VALUES (7,'Edda_Kesby_4@hotmail.com','EddaKesby','Edda','Kesby','6/1/1961');
INSERT INTO [dbo].[User] VALUES (8,'Hank_Autaubo_27@hotmail.com','HankAutaubo','Hank','Autaubo','8/9/1970');
INSERT INTO [dbo].[User] VALUES (9,'Elliott_Labkovsky_37@hotmail.com','ElliottLabkovsky','Elliott','Labkovsky','11/14/1974');
INSERT INTO [dbo].[User] VALUES (10,'Ranae_Bonam_61@hotmail.com','RanaeBonam','Ranae','Bonam','5/12/1984');
INSERT INTO [dbo].[User] VALUES (11,'Shaunte_Damiani_87@hotmail.com','ShaunteDamiani','Shaunte','Damiani','1/5/1995');
INSERT INTO [dbo].[User] VALUES (12,'Earlie_Dickeson_30@hotmail.com','EarlieDickeson','Earlie','Dickeson','12/31/1971');
INSERT INTO [dbo].[User] VALUES (13,'Aletha_Eckl_29@hotmail.com','AlethaEckl','Aletha','Eckl','6/10/1971');
INSERT INTO [dbo].[User] VALUES (14,'Kecia_Baehr_63@hotmail.com','KeciaBaehr','Kecia','Baehr','4/13/1985');
INSERT INTO [dbo].[User] VALUES (15,'Marcene_Tichnell_40@hotmail.com','MarceneTichnell','Marcene','Tichnell','12/17/1975');
INSERT INTO [dbo].[User] VALUES (16,'Gwenda_Ceron_56@hotmail.com','GwendaCeron','Gwenda','Ceron','6/21/1982');
INSERT INTO [dbo].[User] VALUES (17,'Migdalia_Contorno_39@hotmail.com','MigdaliaContorno','Migdalia','Contorno','5/16/1975');
INSERT INTO [dbo].[User] VALUES (18,'Abigail_Thieme_88@hotmail.com','AbigailThieme','Abigail','Thieme','3/18/1995');
INSERT INTO [dbo].[User] VALUES (19,'Karie_Brendel_97@hotmail.com','KarieBrendel','Karie','Brendel','1/15/1999');
INSERT INTO [dbo].[User] VALUES (20,'Stacey_Bundick_55@hotmail.com','StaceyBundick','Stacey','Bundick','3/11/1982');
INSERT INTO [dbo].[User] VALUES (21,'Effie_Roeske_97@hotmail.com','EffieRoeske','Effie','Roeske','2/22/1999');
INSERT INTO [dbo].[User] VALUES (22,'Sam_Nasworthy_97@hotmail.com','SamNasworthy','Sam','Nasworthy','11/19/1998');
INSERT INTO [dbo].[User] VALUES (23,'Kenya_Vansise_3@hotmail.com','KenyaVansise','Kenya','Vansise','1/17/1961');
INSERT INTO [dbo].[User] VALUES (24,'Cherri_Ormsby_19@hotmail.com','CherriOrmsby','Cherri','Ormsby','4/25/1967');
INSERT INTO [dbo].[User] VALUES (25,'Marget_Duggan_7@hotmail.com','MargetDuggan','Marget','Duggan','6/13/1962');
INSERT INTO [dbo].[User] VALUES (26,'Zoe_Behlen_89@hotmail.com','ZoeBehlen','Zoe','Behlen','9/21/1995');
INSERT INTO [dbo].[User] VALUES (27,'Veola_Grigsby_61@hotmail.com','VeolaGrigsby','Veola','Grigsby','7/2/1984');
INSERT INTO [dbo].[User] VALUES (28,'Paul_Lagerstedt_91@hotmail.com','PaulLagerstedt','Paul','Lagerstedt','7/23/1996');
INSERT INTO [dbo].[User] VALUES (29,'Dorthea_Richard_32@hotmail.com','DortheaRichard','Dorthea','Richard','8/19/1972');
INSERT INTO [dbo].[User] VALUES (30,'Josephine_Hostetler_65@hotmail.com','JosephineHostetler','Josephine','Hostetler','12/10/1985');
INSERT INTO [dbo].[User] VALUES (31,'Diedre_Saccone_16@hotmail.com','DiedreSaccone','Diedre','Saccone','5/15/1966');
INSERT INTO [dbo].[User] VALUES (32,'Maryland_Badour_90@hotmail.com','MarylandBadour','Maryland','Badour','5/12/1996');
INSERT INTO [dbo].[User] VALUES (33,'Todd_Boratko_15@hotmail.com','ToddBoratko','Todd','Boratko','10/15/1965');
INSERT INTO [dbo].[User] VALUES (34,'Nevada_Risius_33@hotmail.com','NevadaRisius','Nevada','Risius','2/25/1973');
INSERT INTO [dbo].[User] VALUES (35,'Dana_Nerenberg_77@hotmail.com','DanaNerenberg','Dana','Nerenberg','10/11/1990');
INSERT INTO [dbo].[User] VALUES (36,'Tierra_Ouderkirk_18@hotmail.com','TierraOuderkirk','Tierra','Ouderkirk','3/22/1967');
INSERT INTO [dbo].[User] VALUES (37,'Layne_Bordley_7@hotmail.com','LayneBordley','Layne','Bordley','9/20/1962');
INSERT INTO [dbo].[User] VALUES (38,'Somer_Lippa_22@hotmail.com','SomerLippa','Somer','Lippa','7/13/1968');
INSERT INTO [dbo].[User] VALUES (39,'Marcos_Swims_56@hotmail.com','MarcosSwims','Marcos','Swims','4/7/1982');
INSERT INTO [dbo].[User] VALUES (40,'Carissa_Jopling_73@hotmail.com','CarissaJopling','Carissa','Jopling','3/28/1989');
INSERT INTO [dbo].[User] VALUES (41,'Shirlee_Stotts_57@hotmail.com','ShirleeStotts','Shirlee','Stotts','9/24/1982');
INSERT INTO [dbo].[User] VALUES (42,'Gina_Placzek_63@hotmail.com','GinaPlaczek','Gina','Placzek','5/1/1985');
INSERT INTO [dbo].[User] VALUES (43,'Sydney_Bryton_86@hotmail.com','SydneyBryton','Sydney','Bryton','6/13/1994');
INSERT INTO [dbo].[User] VALUES (44,'Shelli_Coxey_82@hotmail.com','ShelliCoxey','Shelli','Coxey','12/31/1992');
INSERT INTO [dbo].[User] VALUES (45,'Eliz_Lestelle_76@hotmail.com','ElizLestelle','Eliz','Lestelle','8/2/1990');
INSERT INTO [dbo].[User] VALUES (46,'Scott_Schantz_3@hotmail.com','ScottSchantz','Scott','Schantz','1/2/1961');
INSERT INTO [dbo].[User] VALUES (47,'Sunni_Mainiero_48@hotmail.com','SunniMainiero','Sunni','Mainiero','5/3/1979');
INSERT INTO [dbo].[User] VALUES (48,'Sarina_Hince_94@hotmail.com','SarinaHince','Sarina','Hince','10/20/1997');
INSERT INTO [dbo].[User] VALUES (49,'Hyman_Vachula_49@hotmail.com','HymanVachula','Hyman','Vachula','6/18/1979');
INSERT INTO [dbo].[User] VALUES (50,'Santina_Dormane_88@hotmail.com','SantinaDormane','Santina','Dormane','6/20/1995');
INSERT INTO [dbo].[User] VALUES (51,'Maxwell_Thraen_19@hotmail.com','MaxwellThraen','Maxwell','Thraen','6/24/1967');
INSERT INTO [dbo].[User] VALUES (52,'Pricilla_Oetting_50@hotmail.com','PricillaOetting','Pricilla','Oetting','2/29/1980');
INSERT INTO [dbo].[User] VALUES (53,'Anjanette_Pliego_22@hotmail.com','AnjanettePliego','Anjanette','Pliego','9/24/1968');
INSERT INTO [dbo].[User] VALUES (54,'Dino_Rohrer_89@hotmail.com','DinoRohrer','Dino','Rohrer','11/27/1995');
INSERT INTO [dbo].[User] VALUES (55,'Clint_Bueche_27@hotmail.com','ClintBueche','Clint','Bueche','9/5/1970');
INSERT INTO [dbo].[User] VALUES (56,'Rene_Lother_74@hotmail.com','ReneLother','Rene','Lother','9/27/1989');
INSERT INTO [dbo].[User] VALUES (57,'Mertie_Tatem_37@hotmail.com','MertieTatem','Mertie','Tatem','11/13/1974');
INSERT INTO [dbo].[User] VALUES (58,'Ciara_Wnuk_27@hotmail.com','CiaraWnuk','Ciara','Wnuk','10/19/1970');
INSERT INTO [dbo].[User] VALUES (59,'Tobie_Littlejohn_86@hotmail.com','TobieLittlejohn','Tobie','Littlejohn','6/2/1994');
INSERT INTO [dbo].[User] VALUES (60,'Dorene_Milare_98@hotmail.com','DoreneMilare','Dorene','Milare','6/1/1999');
INSERT INTO [dbo].[User] VALUES (61,'Marceline_Steinhour_76@hotmail.com','MarcelineSteinhour','Marceline','Steinhour','7/18/1990');
INSERT INTO [dbo].[User] VALUES (62,'Gricelda_Klevjer_13@hotmail.com','GriceldaKlevjer','Gricelda','Klevjer','11/9/1964');
INSERT INTO [dbo].[User] VALUES (63,'Luann_Burpo_94@hotmail.com','LuannBurpo','Luann','Burpo','12/21/1997');
INSERT INTO [dbo].[User] VALUES (64,'Maggie_Mona_72@hotmail.com','MaggieMona','Maggie','Mona','12/5/1988');
INSERT INTO [dbo].[User] VALUES (65,'Nyla_Rosencrantz_45@hotmail.com','NylaRosencrantz','Nyla','Rosencrantz','12/28/1977');
INSERT INTO [dbo].[User] VALUES (66,'Evonne_Guijarro_96@hotmail.com','EvonneGuijarro','Evonne','Guijarro','8/26/1998');
INSERT INTO [dbo].[User] VALUES (67,'Librada_Czachorowski_16@hotmail.com','LibradaCzachorowski','Librada','Czachorowski','3/17/1966');
INSERT INTO [dbo].[User] VALUES (68,'Cindie_Conner_95@hotmail.com','CindieConner','Cindie','Conner','4/15/1998');
INSERT INTO [dbo].[User] VALUES (69,'Wanetta_Vanisouvong_86@hotmail.com','WanettaVanisouvong','Wanetta','Vanisouvong','7/4/1994');
INSERT INTO [dbo].[User] VALUES (70,'Courtney_Gastello_22@hotmail.com','CourtneyGastello','Courtney','Gastello','9/26/1968');
INSERT INTO [dbo].[User] VALUES (71,'Janina_Spittler_49@hotmail.com','JaninaSpittler','Janina','Spittler','10/1/1979');
INSERT INTO [dbo].[User] VALUES (72,'Cheyenne_Jitchaku_17@hotmail.com','CheyenneJitchaku','Cheyenne','Jitchaku','11/2/1966');
INSERT INTO [dbo].[User] VALUES (73,'Bruno_Banzhaf_33@hotmail.com','BrunoBanzhaf','Bruno','Banzhaf','12/10/1972');
INSERT INTO [dbo].[User] VALUES (74,'Launa_Lonas_25@hotmail.com','LaunaLonas','Launa','Lonas','10/19/1969');
INSERT INTO [dbo].[User] VALUES (75,'Alishia_Whittum_98@hotmail.com','AlishiaWhittum','Alishia','Whittum','6/17/1999');
INSERT INTO [dbo].[User] VALUES (76,'Ariel_Pulos_35@hotmail.com','ArielPulos','Ariel','Pulos','10/23/1973');
INSERT INTO [dbo].[User] VALUES (77,'Earlene_Sturrock_11@hotmail.com','EarleneSturrock','Earlene','Sturrock','6/7/1964');
INSERT INTO [dbo].[User] VALUES (78,'Bobby_Teet_20@hotmail.com','BobbyTeet','Bobby','Teet','1/18/1968');
INSERT INTO [dbo].[User] VALUES (79,'Sherise_Stovall_42@hotmail.com','SheriseStovall','Sherise','Stovall','9/23/1976');
INSERT INTO [dbo].[User] VALUES (80,'Kelsey_Panich_4@hotmail.com','KelseyPanich','Kelsey','Panich','6/10/1961');
INSERT INTO [dbo].[User] VALUES (81,'Pedro_Coakley_41@hotmail.com','PedroCoakley','Pedro','Coakley','5/20/1976');
INSERT INTO [dbo].[User] VALUES (82,'Jamar_Goldstone_67@hotmail.com','JamarGoldstone','Jamar','Goldstone','9/12/1986');
INSERT INTO [dbo].[User] VALUES (83,'Shana_Digirolomo_43@hotmail.com','ShanaDigirolomo','Shana','Digirolomo','2/5/1977');
INSERT INTO [dbo].[User] VALUES (84,'Celina_Rendell_43@hotmail.com','CelinaRendell','Celina','Rendell','3/1/1977');
INSERT INTO [dbo].[User] VALUES (85,'Breanne_Garvie_46@hotmail.com','BreanneGarvie','Breanne','Garvie','6/18/1978');
INSERT INTO [dbo].[User] VALUES (86,'Velma_Scrivens_65@hotmail.com','VelmaScrivens','Velma','Scrivens','3/17/1986');
INSERT INTO [dbo].[User] VALUES (87,'Georgine_Lange_69@hotmail.com','GeorgineLange','Georgine','Lange','8/19/1987');
INSERT INTO [dbo].[User] VALUES (88,'Latrisha_Andras_25@hotmail.com','LatrishaAndras','Latrisha','Andras','11/19/1969');
INSERT INTO [dbo].[User] VALUES (89,'Oma_Walkley_7@hotmail.com','OmaWalkley','Oma','Walkley','6/22/1962');
INSERT INTO [dbo].[User] VALUES (90,'Judith_Shintaku_3@hotmail.com','JudithShintaku','Judith','Shintaku','1/13/1961');
INSERT INTO [dbo].[User] VALUES (91,'Dione_Gividen_81@hotmail.com','DioneGividen','Dione','Gividen','5/9/1992');
INSERT INTO [dbo].[User] VALUES (92,'Marvis_Gleeson_80@hotmail.com','MarvisGleeson','Marvis','Gleeson','12/2/1991');
INSERT INTO [dbo].[User] VALUES (93,'Leah_Skoien_35@hotmail.com','LeahSkoien','Leah','Skoien','2/10/1974');
INSERT INTO [dbo].[User] VALUES (94,'Sherri_Saini_57@hotmail.com','SherriSaini','Sherri','Saini','11/6/1982');
INSERT INTO [dbo].[User] VALUES (95,'Elina_Tynes_96@hotmail.com','ElinaTynes','Elina','Tynes','9/11/1998');
INSERT INTO [dbo].[User] VALUES (96,'Brittny_Weissman_45@hotmail.com','BrittnyWeissman','Brittny','Weissman','11/15/1977');
INSERT INTO [dbo].[User] VALUES (97,'Isidra_Carbone_68@hotmail.com','IsidraCarbone','Isidra','Carbone','5/12/1987');
INSERT INTO [dbo].[User] VALUES (98,'Basilia_Foard_14@hotmail.com','BasiliaFoard','Basilia','Foard','7/8/1965');
INSERT INTO [dbo].[User] VALUES (99,'Faye_Emond_38@hotmail.com','FayeEmond','Faye','Emond','1/4/1975');
INSERT INTO [dbo].[User] VALUES (100,'Leo_Kenefick_80@hotmail.com','LeoKenefick','Leo','Kenefick','12/8/1991');
INSERT INTO [dbo].[User] VALUES (101,'Chery_Presswood_87@hotmail.com','CheryPresswood','Chery','Presswood','10/18/1994');
INSERT INTO [dbo].[User] VALUES (102,'Apryl_Wolslegel_53@hotmail.com','AprylWolslegel','Apryl','Wolslegel','1/18/1981');
INSERT INTO [dbo].[User] VALUES (103,'Tarsha_Cloutman_9@hotmail.com','TarshaCloutman','Tarsha','Cloutman','4/18/1963');
INSERT INTO [dbo].[User] VALUES (104,'Lovie_Esperon_27@hotmail.com','LovieEsperon','Lovie','Esperon','9/21/1970');
INSERT INTO [dbo].[User] VALUES (105,'Sang_Schoderbek_39@hotmail.com','SangSchoderbek','Sang','Schoderbek','9/19/1975');
INSERT INTO [dbo].[User] VALUES (106,'Ria_Saint_2@hotmail.com','RiaSaint','Ria','Saint','8/21/1960');
INSERT INTO [dbo].[User] VALUES (107,'Shantel_Starck_18@hotmail.com','ShantelStarck','Shantel','Starck','3/21/1967');
INSERT INTO [dbo].[User] VALUES (108,'Sue_Pignataro_97@hotmail.com','SuePignataro','Sue','Pignataro','12/6/1998');
INSERT INTO [dbo].[User] VALUES (109,'Sherron_Vassure_91@hotmail.com','SherronVassure','Sherron','Vassure','6/11/1996');
INSERT INTO [dbo].[User] VALUES (110,'Cassidy_Sandstrom_92@hotmail.com','CassidySandstrom','Cassidy','Sandstrom','11/13/1996');
INSERT INTO [dbo].[User] VALUES (111,'Latashia_Busacker_63@hotmail.com','LatashiaBusacker','Latashia','Busacker','4/21/1985');
INSERT INTO [dbo].[User] VALUES (112,'Marisha_Eckhardt_17@hotmail.com','MarishaEckhardt','Marisha','Eckhardt','10/27/1966');
INSERT INTO [dbo].[User] VALUES (113,'Odilia_Viveiros_85@hotmail.com','OdiliaViveiros','Odilia','Viveiros','1/26/1994');
INSERT INTO [dbo].[User] VALUES (114,'Sherilyn_Durun_82@hotmail.com','SherilynDurun','Sherilyn','Durun','12/22/1992');
INSERT INTO [dbo].[User] VALUES (115,'Burton_Desparrois_58@hotmail.com','BurtonDesparrois','Burton','Desparrois','1/12/1983');
INSERT INTO [dbo].[User] VALUES (116,'Yasmin_Longbrake_10@hotmail.com','YasminLongbrake','Yasmin','Longbrake','11/5/1963');
INSERT INTO [dbo].[User] VALUES (117,'Max_Lebaron_69@hotmail.com','MaxLebaron','Max','Lebaron','10/5/1987');
INSERT INTO [dbo].[User] VALUES (118,'Isa_Dimas_52@hotmail.com','IsaDimas','Isa','Dimas','10/21/1980');
INSERT INTO [dbo].[User] VALUES (119,'Mariano_Coppolino_26@hotmail.com','MarianoCoppolino','Mariano','Coppolino','6/19/1970');
INSERT INTO [dbo].[User] VALUES (120,'Evangelina_Daws_79@hotmail.com','EvangelinaDaws','Evangelina','Daws','10/14/1991');
INSERT INTO [dbo].[User] VALUES (121,'Denese_Baysinger_28@hotmail.com','DeneseBaysinger','Denese','Baysinger','1/8/1971');
INSERT INTO [dbo].[User] VALUES (122,'Sherlyn_Lanphear_90@hotmail.com','SherlynLanphear','Sherlyn','Lanphear','4/28/1996');
INSERT INTO [dbo].[User] VALUES (123,'Keith_Doescher_89@hotmail.com','KeithDoescher','Keith','Doescher','10/24/1995');
INSERT INTO [dbo].[User] VALUES (124,'Renda_Tullis_83@hotmail.com','RendaTullis','Renda','Tullis','6/21/1993');
INSERT INTO [dbo].[User] VALUES (125,'Walter_Yahn_41@hotmail.com','WalterYahn','Walter','Yahn','5/20/1976');
INSERT INTO [dbo].[User] VALUES (126,'Penni_Schnelder_69@hotmail.com','PenniSchnelder','Penni','Schnelder','10/30/1987');
INSERT INTO [dbo].[User] VALUES (127,'Yoko_Tonne_81@hotmail.com','YokoTonne','Yoko','Tonne','9/22/1992');
INSERT INTO [dbo].[User] VALUES (128,'Monroe_Antes_75@hotmail.com','MonroeAntes','Monroe','Antes','2/4/1990');
INSERT INTO [dbo].[User] VALUES (129,'Jonelle_Flakne_28@hotmail.com','JonelleFlakne','Jonelle','Flakne','2/8/1971');
INSERT INTO [dbo].[User] VALUES (130,'Rochel_Ziebol_54@hotmail.com','RochelZiebol','Rochel','Ziebol','8/2/1981');
INSERT INTO [dbo].[User] VALUES (131,'Liana_Marone_66@hotmail.com','LianaMarone','Liana','Marone','6/14/1986');
INSERT INTO [dbo].[User] VALUES (132,'Patrick_Wildridge_97@hotmail.com','PatrickWildridge','Patrick','Wildridge','12/1/1998');
INSERT INTO [dbo].[User] VALUES (133,'Verlie_Zaborski_82@hotmail.com','VerlieZaborski','Verlie','Zaborski','1/13/1993');
INSERT INTO [dbo].[User] VALUES (134,'Joana_Crays_62@hotmail.com','JoanaCrays','Joana','Crays','10/16/1984');
INSERT INTO [dbo].[User] VALUES (135,'Jeanne_Lame_17@hotmail.com','JeanneLame','Jeanne','Lame','8/24/1966');
INSERT INTO [dbo].[User] VALUES (136,'Ceola_Cokely_88@hotmail.com','CeolaCokely','Ceola','Cokely','5/3/1995');
INSERT INTO [dbo].[User] VALUES (137,'Nicola_Goike_58@hotmail.com','NicolaGoike','Nicola','Goike','5/27/1983');
INSERT INTO [dbo].[User] VALUES (138,'Adan_Been_16@hotmail.com','AdanBeen','Adan','Been','5/17/1966');
INSERT INTO [dbo].[User] VALUES (139,'Ginger_Xiao_4@hotmail.com','GingerXiao','Ginger','Xiao','6/13/1961');
INSERT INTO [dbo].[User] VALUES (140,'Stormy_Munuz_45@hotmail.com','StormyMunuz','Stormy','Munuz','10/27/1977');
INSERT INTO [dbo].[User] VALUES (141,'Jerica_Herauf_47@hotmail.com','JericaHerauf','Jerica','Herauf','12/27/1978');
INSERT INTO [dbo].[User] VALUES (142,'Arron_Nonamaker_72@hotmail.com','ArronNonamaker','Arron','Nonamaker','9/12/1988');
INSERT INTO [dbo].[User] VALUES (143,'Tanika_Silao_34@hotmail.com','TanikaSilao','Tanika','Silao','6/9/1973');
INSERT INTO [dbo].[User] VALUES (144,'Pearle_Mcmillin_14@hotmail.com','PearleMcmillin','Pearle','Mcmillin','8/8/1965');
INSERT INTO [dbo].[User] VALUES (145,'Karin_Ripa_39@hotmail.com','KarinRipa','Karin','Ripa','9/24/1975');
INSERT INTO [dbo].[User] VALUES (146,'Lynne_Hopkins_64@hotmail.com','LynneHopkins','Lynne','Hopkins','7/14/1985');
INSERT INTO [dbo].[User] VALUES (147,'Trish_Croley_94@hotmail.com','TrishCroley','Trish','Croley','11/6/1997');
INSERT INTO [dbo].[User] VALUES (148,'Ines_Klukan_53@hotmail.com','InesKlukan','Ines','Klukan','2/18/1981');
INSERT INTO [dbo].[User] VALUES (149,'Tim_Rio_99@hotmail.com','TimRio','Tim','Rio','10/26/1999');
INSERT INTO [dbo].[User] VALUES (150,'Maricruz_Stockfisch_87@hotmail.com','MaricruzStockfisch','Maricruz','Stockfisch','11/6/1994');
INSERT INTO [dbo].[User] VALUES (151,'Forest_Manes_75@hotmail.com','ForestManes','Forest','Manes','2/11/1990');
INSERT INTO [dbo].[User] VALUES (152,'Mireille_Schwantd_17@hotmail.com','MireilleSchwantd','Mireille','Schwantd','7/21/1966');
INSERT INTO [dbo].[User] VALUES (153,'Earline_Dittrick_87@hotmail.com','EarlineDittrick','Earline','Dittrick','1/19/1995');
INSERT INTO [dbo].[User] VALUES (154,'Dori_Roylance_58@hotmail.com','DoriRoylance','Dori','Roylance','3/24/1983');
INSERT INTO [dbo].[User] VALUES (155,'Leisa_Dardagnac_52@hotmail.com','LeisaDardagnac','Leisa','Dardagnac','11/30/1980');
INSERT INTO [dbo].[User] VALUES (156,'Meri_Snowdon_96@hotmail.com','MeriSnowdon','Meri','Snowdon','6/21/1998');
INSERT INTO [dbo].[User] VALUES (157,'Alyce_Cartner_63@hotmail.com','AlyceCartner','Alyce','Cartner','3/27/1985');
INSERT INTO [dbo].[User] VALUES (158,'Marian_Lauren_25@hotmail.com','MarianLauren','Marian','Lauren','10/28/1969');
INSERT INTO [dbo].[User] VALUES (159,'Bryant_Finey_85@hotmail.com','BryantFiney','Bryant','Finey','5/4/1994');
INSERT INTO [dbo].[User] VALUES (160,'Lucas_Deep_70@hotmail.com','LucasDeep','Lucas','Deep','11/20/1987');
INSERT INTO [dbo].[User] VALUES (161,'Soo_Deakin_20@hotmail.com','SooDeakin','Soo','Deakin','11/30/1967');
INSERT INTO [dbo].[User] VALUES (162,'Horacio_Canak_43@hotmail.com','HoracioCanak','Horacio','Canak','2/14/1977');
INSERT INTO [dbo].[User] VALUES (163,'Jenette_Zabarkes_69@hotmail.com','JenetteZabarkes','Jenette','Zabarkes','10/29/1987');
INSERT INTO [dbo].[User] VALUES (164,'Ruthe_Stokely_37@hotmail.com','RutheStokely','Ruthe','Stokely','11/10/1974');
INSERT INTO [dbo].[User] VALUES (165,'Wilmer_Rehling_26@hotmail.com','WilmerRehling','Wilmer','Rehling','6/2/1970');
INSERT INTO [dbo].[User] VALUES (166,'Casey_Landgren_66@hotmail.com','CaseyLandgren','Casey','Landgren','5/22/1986');
INSERT INTO [dbo].[User] VALUES (167,'Tina_Lemle_35@hotmail.com','TinaLemle','Tina','Lemle','10/13/1973');
INSERT INTO [dbo].[User] VALUES (168,'Hedy_Emfield_23@hotmail.com','HedyEmfield','Hedy','Emfield','4/11/1969');
INSERT INTO [dbo].[User] VALUES (169,'Britney_Sperry_66@hotmail.com','BritneySperry','Britney','Sperry','5/1/1986');
INSERT INTO [dbo].[User] VALUES (170,'Else_Olewine_69@hotmail.com','ElseOlewine','Else','Olewine','9/12/1987');
INSERT INTO [dbo].[User] VALUES (171,'Benton_Iverslie_51@hotmail.com','BentonIverslie','Benton','Iverslie','6/10/1980');
INSERT INTO [dbo].[User] VALUES (172,'Manda_Mizer_53@hotmail.com','MandaMizer','Manda','Mizer','5/20/1981');
INSERT INTO [dbo].[User] VALUES (173,'Emmitt_Owenby_48@hotmail.com','EmmittOwenby','Emmitt','Owenby','5/11/1979');
INSERT INTO [dbo].[User] VALUES (174,'Kayleigh_Nocket_81@hotmail.com','KayleighNocket','Kayleigh','Nocket','8/22/1992');
INSERT INTO [dbo].[User] VALUES (175,'Mariko_Kershaw_32@hotmail.com','MarikoKershaw','Mariko','Kershaw','10/17/1972');
INSERT INTO [dbo].[User] VALUES (176,'Matt_Surles_56@hotmail.com','MattSurles','Matt','Surles','4/27/1982');
INSERT INTO [dbo].[User] VALUES (177,'Anthony_Minteer_57@hotmail.com','AnthonyMinteer','Anthony','Minteer','11/19/1982');
INSERT INTO [dbo].[User] VALUES (178,'Vincenza_Estella_75@hotmail.com','VincenzaEstella','Vincenza','Estella','3/17/1990');
INSERT INTO [dbo].[User] VALUES (179,'Donita_Kaiktsian_44@hotmail.com','DonitaKaiktsian','Donita','Kaiktsian','9/27/1977');
INSERT INTO [dbo].[User] VALUES (180,'Berniece_Luvianos_77@hotmail.com','BernieceLuvianos','Berniece','Luvianos','11/6/1990');
INSERT INTO [dbo].[User] VALUES (181,'Mechelle_Bingler_75@hotmail.com','MechelleBingler','Mechelle','Bingler','12/24/1989');
INSERT INTO [dbo].[User] VALUES (182,'Cedric_Gilgan_29@hotmail.com','CedricGilgan','Cedric','Gilgan','8/4/1971');
INSERT INTO [dbo].[User] VALUES (183,'Tammy_Peschel_75@hotmail.com','TammyPeschel','Tammy','Peschel','4/12/1990');
INSERT INTO [dbo].[User] VALUES (184,'Cicely_Pestka_41@hotmail.com','CicelyPestka','Cicely','Pestka','4/3/1976');
INSERT INTO [dbo].[User] VALUES (185,'Jenifer_Vicencio_78@hotmail.com','JeniferVicencio','Jenifer','Vicencio','6/22/1991');
INSERT INTO [dbo].[User] VALUES (186,'Susann_Zelkin_50@hotmail.com','SusannZelkin','Susann','Zelkin','11/25/1979');
INSERT INTO [dbo].[User] VALUES (187,'Thresa_Reeh_10@hotmail.com','ThresaReeh','Thresa','Reeh','11/12/1963');
INSERT INTO [dbo].[User] VALUES (188,'Mee_Jerde_25@hotmail.com','MeeJerde','Mee','Jerde','10/23/1969');
INSERT INTO [dbo].[User] VALUES (189,'Thora_Figueiras_10@hotmail.com','ThoraFigueiras','Thora','Figueiras','11/17/1963');
INSERT INTO [dbo].[User] VALUES (190,'Bettye_Lindel_21@hotmail.com','BettyeLindel','Bettye','Lindel','3/4/1968');
INSERT INTO [dbo].[User] VALUES (191,'Renaldo_Hamasaki_25@hotmail.com','RenaldoHamasaki','Renaldo','Hamasaki','2/6/1970');
INSERT INTO [dbo].[User] VALUES (192,'Marla_Brodell_34@hotmail.com','MarlaBrodell','Marla','Brodell','7/30/1973');
INSERT INTO [dbo].[User] VALUES (193,'Frida_Kissling_30@hotmail.com','FridaKissling','Frida','Kissling','1/14/1972');
INSERT INTO [dbo].[User] VALUES (194,'Noelia_Adamec_34@hotmail.com','NoeliaAdamec','Noelia','Adamec','7/24/1973');
INSERT INTO [dbo].[User] VALUES (195,'Jeane_Mcgunnigle_25@hotmail.com','JeaneMcgunnigle','Jeane','Mcgunnigle','11/28/1969');
INSERT INTO [dbo].[User] VALUES (196,'Laila_Ruane_5@hotmail.com','LailaRuane','Laila','Ruane','11/11/1961');
INSERT INTO [dbo].[User] VALUES (197,'Pat_Creasman_3@hotmail.com','PatCreasman','Pat','Creasman','11/14/1960');
INSERT INTO [dbo].[User] VALUES (198,'Tamekia_Villalvazo_96@hotmail.com','TamekiaVillalvazo','Tamekia','Villalvazo','7/31/1998');
INSERT INTO [dbo].[User] VALUES (199,'Cristina_Eslick_88@hotmail.com','CristinaEslick','Cristina','Eslick','3/9/1995');
INSERT INTO [dbo].[User] VALUES (200,'Annamae_Wiesen_73@hotmail.com','AnnamaeWiesen','Annamae','Wiesen','5/4/1989');

INSERT INTO [dbo].[UserToTag] VALUES (9,1);
INSERT INTO [dbo].[UserToTag] VALUES (8,1);
INSERT INTO [dbo].[UserToTag] VALUES (6,1);
INSERT INTO [dbo].[UserToTag] VALUES (5,2);
INSERT INTO [dbo].[UserToTag] VALUES (9,2);
INSERT INTO [dbo].[UserToTag] VALUES (9,3);
INSERT INTO [dbo].[UserToTag] VALUES (8,3);
INSERT INTO [dbo].[UserToTag] VALUES (8,4);
INSERT INTO [dbo].[UserToTag] VALUES (3,4);
INSERT INTO [dbo].[UserToTag] VALUES (6,4);
INSERT INTO [dbo].[UserToTag] VALUES (9,4);
INSERT INTO [dbo].[UserToTag] VALUES (5,5);
INSERT INTO [dbo].[UserToTag] VALUES (6,5);
INSERT INTO [dbo].[UserToTag] VALUES (8,5);
INSERT INTO [dbo].[UserToTag] VALUES (2,5);
INSERT INTO [dbo].[UserToTag] VALUES (9,6);
INSERT INTO [dbo].[UserToTag] VALUES (3,6);
INSERT INTO [dbo].[UserToTag] VALUES (4,7);
INSERT INTO [dbo].[UserToTag] VALUES (8,8);
INSERT INTO [dbo].[UserToTag] VALUES (9,8);
INSERT INTO [dbo].[UserToTag] VALUES (10,9);
INSERT INTO [dbo].[UserToTag] VALUES (5,9);
INSERT INTO [dbo].[UserToTag] VALUES (4,10);
INSERT INTO [dbo].[UserToTag] VALUES (7,10);
INSERT INTO [dbo].[UserToTag] VALUES (3,10);
INSERT INTO [dbo].[UserToTag] VALUES (7,11);
INSERT INTO [dbo].[UserToTag] VALUES (1,11);
INSERT INTO [dbo].[UserToTag] VALUES (9,11);
INSERT INTO [dbo].[UserToTag] VALUES (5,11);
INSERT INTO [dbo].[UserToTag] VALUES (6,12);
INSERT INTO [dbo].[UserToTag] VALUES (8,12);
INSERT INTO [dbo].[UserToTag] VALUES (3,13);
INSERT INTO [dbo].[UserToTag] VALUES (10,13);
INSERT INTO [dbo].[UserToTag] VALUES (6,14);
INSERT INTO [dbo].[UserToTag] VALUES (8,14);
INSERT INTO [dbo].[UserToTag] VALUES (1,14);
INSERT INTO [dbo].[UserToTag] VALUES (6,15);
INSERT INTO [dbo].[UserToTag] VALUES (3,15);
INSERT INTO [dbo].[UserToTag] VALUES (1,16);
INSERT INTO [dbo].[UserToTag] VALUES (2,16);
INSERT INTO [dbo].[UserToTag] VALUES (9,16);
INSERT INTO [dbo].[UserToTag] VALUES (2,17);
INSERT INTO [dbo].[UserToTag] VALUES (3,17);
INSERT INTO [dbo].[UserToTag] VALUES (8,18);
INSERT INTO [dbo].[UserToTag] VALUES (7,18);
INSERT INTO [dbo].[UserToTag] VALUES (10,18);
INSERT INTO [dbo].[UserToTag] VALUES (9,18);
INSERT INTO [dbo].[UserToTag] VALUES (3,19);
INSERT INTO [dbo].[UserToTag] VALUES (10,19);
INSERT INTO [dbo].[UserToTag] VALUES (2,19);
INSERT INTO [dbo].[UserToTag] VALUES (7,19);
INSERT INTO [dbo].[UserToTag] VALUES (4,20);
INSERT INTO [dbo].[UserToTag] VALUES (5,20);
INSERT INTO [dbo].[UserToTag] VALUES (8,20);
INSERT INTO [dbo].[UserToTag] VALUES (2,21);
INSERT INTO [dbo].[UserToTag] VALUES (9,21);
INSERT INTO [dbo].[UserToTag] VALUES (6,21);
INSERT INTO [dbo].[UserToTag] VALUES (10,21);
INSERT INTO [dbo].[UserToTag] VALUES (3,22);
INSERT INTO [dbo].[UserToTag] VALUES (5,22);
INSERT INTO [dbo].[UserToTag] VALUES (2,22);
INSERT INTO [dbo].[UserToTag] VALUES (9,22);
INSERT INTO [dbo].[UserToTag] VALUES (2,23);
INSERT INTO [dbo].[UserToTag] VALUES (4,24);
INSERT INTO [dbo].[UserToTag] VALUES (2,25);
INSERT INTO [dbo].[UserToTag] VALUES (5,26);
INSERT INTO [dbo].[UserToTag] VALUES (2,26);
INSERT INTO [dbo].[UserToTag] VALUES (3,26);
INSERT INTO [dbo].[UserToTag] VALUES (9,26);
INSERT INTO [dbo].[UserToTag] VALUES (5,27);
INSERT INTO [dbo].[UserToTag] VALUES (7,27);
INSERT INTO [dbo].[UserToTag] VALUES (2,27);
INSERT INTO [dbo].[UserToTag] VALUES (8,28);
INSERT INTO [dbo].[UserToTag] VALUES (7,28);
INSERT INTO [dbo].[UserToTag] VALUES (4,28);
INSERT INTO [dbo].[UserToTag] VALUES (3,28);
INSERT INTO [dbo].[UserToTag] VALUES (8,29);
INSERT INTO [dbo].[UserToTag] VALUES (1,29);
INSERT INTO [dbo].[UserToTag] VALUES (5,30);
INSERT INTO [dbo].[UserToTag] VALUES (8,30);
INSERT INTO [dbo].[UserToTag] VALUES (7,30);
INSERT INTO [dbo].[UserToTag] VALUES (1,31);
INSERT INTO [dbo].[UserToTag] VALUES (2,32);
INSERT INTO [dbo].[UserToTag] VALUES (7,32);
INSERT INTO [dbo].[UserToTag] VALUES (8,32);
INSERT INTO [dbo].[UserToTag] VALUES (10,32);
INSERT INTO [dbo].[UserToTag] VALUES (5,33);
INSERT INTO [dbo].[UserToTag] VALUES (4,34);
INSERT INTO [dbo].[UserToTag] VALUES (1,34);
INSERT INTO [dbo].[UserToTag] VALUES (6,35);
INSERT INTO [dbo].[UserToTag] VALUES (3,35);
INSERT INTO [dbo].[UserToTag] VALUES (7,35);
INSERT INTO [dbo].[UserToTag] VALUES (9,35);
INSERT INTO [dbo].[UserToTag] VALUES (9,36);
INSERT INTO [dbo].[UserToTag] VALUES (6,37);
INSERT INTO [dbo].[UserToTag] VALUES (2,38);
INSERT INTO [dbo].[UserToTag] VALUES (8,39);
INSERT INTO [dbo].[UserToTag] VALUES (6,39);
INSERT INTO [dbo].[UserToTag] VALUES (9,39);
INSERT INTO [dbo].[UserToTag] VALUES (8,40);
INSERT INTO [dbo].[UserToTag] VALUES (1,40);
INSERT INTO [dbo].[UserToTag] VALUES (6,40);
INSERT INTO [dbo].[UserToTag] VALUES (3,41);
INSERT INTO [dbo].[UserToTag] VALUES (8,41);
INSERT INTO [dbo].[UserToTag] VALUES (2,41);
INSERT INTO [dbo].[UserToTag] VALUES (6,42);
INSERT INTO [dbo].[UserToTag] VALUES (2,42);
INSERT INTO [dbo].[UserToTag] VALUES (8,42);
INSERT INTO [dbo].[UserToTag] VALUES (9,43);
INSERT INTO [dbo].[UserToTag] VALUES (8,43);
INSERT INTO [dbo].[UserToTag] VALUES (3,43);
INSERT INTO [dbo].[UserToTag] VALUES (7,43);
INSERT INTO [dbo].[UserToTag] VALUES (5,44);
INSERT INTO [dbo].[UserToTag] VALUES (1,44);
INSERT INTO [dbo].[UserToTag] VALUES (6,44);
INSERT INTO [dbo].[UserToTag] VALUES (7,44);
INSERT INTO [dbo].[UserToTag] VALUES (9,45);
INSERT INTO [dbo].[UserToTag] VALUES (5,45);
INSERT INTO [dbo].[UserToTag] VALUES (6,45);
INSERT INTO [dbo].[UserToTag] VALUES (1,45);
INSERT INTO [dbo].[UserToTag] VALUES (6,46);
INSERT INTO [dbo].[UserToTag] VALUES (3,47);
INSERT INTO [dbo].[UserToTag] VALUES (7,47);
INSERT INTO [dbo].[UserToTag] VALUES (2,48);
INSERT INTO [dbo].[UserToTag] VALUES (7,48);
INSERT INTO [dbo].[UserToTag] VALUES (10,48);
INSERT INTO [dbo].[UserToTag] VALUES (9,48);
INSERT INTO [dbo].[UserToTag] VALUES (4,49);
INSERT INTO [dbo].[UserToTag] VALUES (1,49);
INSERT INTO [dbo].[UserToTag] VALUES (4,50);
INSERT INTO [dbo].[UserToTag] VALUES (10,50);
INSERT INTO [dbo].[UserToTag] VALUES (8,50);
INSERT INTO [dbo].[UserToTag] VALUES (7,50);
INSERT INTO [dbo].[UserToTag] VALUES (1,51);
INSERT INTO [dbo].[UserToTag] VALUES (3,52);
INSERT INTO [dbo].[UserToTag] VALUES (7,52);
INSERT INTO [dbo].[UserToTag] VALUES (1,52);
INSERT INTO [dbo].[UserToTag] VALUES (2,53);
INSERT INTO [dbo].[UserToTag] VALUES (8,54);
INSERT INTO [dbo].[UserToTag] VALUES (7,54);
INSERT INTO [dbo].[UserToTag] VALUES (10,54);
INSERT INTO [dbo].[UserToTag] VALUES (4,54);
INSERT INTO [dbo].[UserToTag] VALUES (7,55);
INSERT INTO [dbo].[UserToTag] VALUES (10,55);
INSERT INTO [dbo].[UserToTag] VALUES (1,56);
INSERT INTO [dbo].[UserToTag] VALUES (2,56);
INSERT INTO [dbo].[UserToTag] VALUES (3,56);
INSERT INTO [dbo].[UserToTag] VALUES (6,57);
INSERT INTO [dbo].[UserToTag] VALUES (3,57);
INSERT INTO [dbo].[UserToTag] VALUES (2,58);
INSERT INTO [dbo].[UserToTag] VALUES (1,58);
INSERT INTO [dbo].[UserToTag] VALUES (4,59);
INSERT INTO [dbo].[UserToTag] VALUES (7,59);
INSERT INTO [dbo].[UserToTag] VALUES (1,59);
INSERT INTO [dbo].[UserToTag] VALUES (10,59);
INSERT INTO [dbo].[UserToTag] VALUES (7,60);
INSERT INTO [dbo].[UserToTag] VALUES (9,60);
INSERT INTO [dbo].[UserToTag] VALUES (10,60);
INSERT INTO [dbo].[UserToTag] VALUES (8,60);
INSERT INTO [dbo].[UserToTag] VALUES (2,61);
INSERT INTO [dbo].[UserToTag] VALUES (3,61);
INSERT INTO [dbo].[UserToTag] VALUES (1,61);
INSERT INTO [dbo].[UserToTag] VALUES (6,61);
INSERT INTO [dbo].[UserToTag] VALUES (4,62);
INSERT INTO [dbo].[UserToTag] VALUES (4,63);
INSERT INTO [dbo].[UserToTag] VALUES (1,63);
INSERT INTO [dbo].[UserToTag] VALUES (10,63);
INSERT INTO [dbo].[UserToTag] VALUES (5,63);
INSERT INTO [dbo].[UserToTag] VALUES (10,64);
INSERT INTO [dbo].[UserToTag] VALUES (4,64);
INSERT INTO [dbo].[UserToTag] VALUES (9,64);
INSERT INTO [dbo].[UserToTag] VALUES (4,65);
INSERT INTO [dbo].[UserToTag] VALUES (1,65);
INSERT INTO [dbo].[UserToTag] VALUES (5,66);
INSERT INTO [dbo].[UserToTag] VALUES (2,66);
INSERT INTO [dbo].[UserToTag] VALUES (7,66);
INSERT INTO [dbo].[UserToTag] VALUES (8,66);
INSERT INTO [dbo].[UserToTag] VALUES (10,67);
INSERT INTO [dbo].[UserToTag] VALUES (3,68);
INSERT INTO [dbo].[UserToTag] VALUES (10,68);
INSERT INTO [dbo].[UserToTag] VALUES (7,68);
INSERT INTO [dbo].[UserToTag] VALUES (6,68);
INSERT INTO [dbo].[UserToTag] VALUES (7,69);
INSERT INTO [dbo].[UserToTag] VALUES (8,69);
INSERT INTO [dbo].[UserToTag] VALUES (4,69);
INSERT INTO [dbo].[UserToTag] VALUES (5,69);
INSERT INTO [dbo].[UserToTag] VALUES (2,70);
INSERT INTO [dbo].[UserToTag] VALUES (10,71);
INSERT INTO [dbo].[UserToTag] VALUES (2,71);
INSERT INTO [dbo].[UserToTag] VALUES (8,72);
INSERT INTO [dbo].[UserToTag] VALUES (9,73);
INSERT INTO [dbo].[UserToTag] VALUES (5,73);
INSERT INTO [dbo].[UserToTag] VALUES (3,74);
INSERT INTO [dbo].[UserToTag] VALUES (9,75);
INSERT INTO [dbo].[UserToTag] VALUES (10,75);
INSERT INTO [dbo].[UserToTag] VALUES (3,75);
INSERT INTO [dbo].[UserToTag] VALUES (7,75);
INSERT INTO [dbo].[UserToTag] VALUES (1,76);
INSERT INTO [dbo].[UserToTag] VALUES (9,76);
INSERT INTO [dbo].[UserToTag] VALUES (4,77);
INSERT INTO [dbo].[UserToTag] VALUES (1,78);
INSERT INTO [dbo].[UserToTag] VALUES (9,79);
INSERT INTO [dbo].[UserToTag] VALUES (7,79);
INSERT INTO [dbo].[UserToTag] VALUES (6,80);
INSERT INTO [dbo].[UserToTag] VALUES (3,81);
INSERT INTO [dbo].[UserToTag] VALUES (4,81);
INSERT INTO [dbo].[UserToTag] VALUES (9,82);
INSERT INTO [dbo].[UserToTag] VALUES (4,82);
INSERT INTO [dbo].[UserToTag] VALUES (6,82);
INSERT INTO [dbo].[UserToTag] VALUES (5,83);
INSERT INTO [dbo].[UserToTag] VALUES (7,83);
INSERT INTO [dbo].[UserToTag] VALUES (4,84);
INSERT INTO [dbo].[UserToTag] VALUES (10,84);
INSERT INTO [dbo].[UserToTag] VALUES (8,85);
INSERT INTO [dbo].[UserToTag] VALUES (2,85);
INSERT INTO [dbo].[UserToTag] VALUES (10,86);
INSERT INTO [dbo].[UserToTag] VALUES (5,86);
INSERT INTO [dbo].[UserToTag] VALUES (2,86);
INSERT INTO [dbo].[UserToTag] VALUES (10,87);
INSERT INTO [dbo].[UserToTag] VALUES (3,87);
INSERT INTO [dbo].[UserToTag] VALUES (2,87);
INSERT INTO [dbo].[UserToTag] VALUES (1,88);
INSERT INTO [dbo].[UserToTag] VALUES (7,89);
INSERT INTO [dbo].[UserToTag] VALUES (2,90);
INSERT INTO [dbo].[UserToTag] VALUES (10,91);
INSERT INTO [dbo].[UserToTag] VALUES (5,91);
INSERT INTO [dbo].[UserToTag] VALUES (1,91);
INSERT INTO [dbo].[UserToTag] VALUES (8,91);
INSERT INTO [dbo].[UserToTag] VALUES (9,92);
INSERT INTO [dbo].[UserToTag] VALUES (1,92);
INSERT INTO [dbo].[UserToTag] VALUES (2,92);
INSERT INTO [dbo].[UserToTag] VALUES (3,92);
INSERT INTO [dbo].[UserToTag] VALUES (2,93);
INSERT INTO [dbo].[UserToTag] VALUES (6,93);
INSERT INTO [dbo].[UserToTag] VALUES (9,94);
INSERT INTO [dbo].[UserToTag] VALUES (2,94);
INSERT INTO [dbo].[UserToTag] VALUES (10,94);
INSERT INTO [dbo].[UserToTag] VALUES (10,95);
INSERT INTO [dbo].[UserToTag] VALUES (9,95);
INSERT INTO [dbo].[UserToTag] VALUES (8,95);
INSERT INTO [dbo].[UserToTag] VALUES (2,95);
INSERT INTO [dbo].[UserToTag] VALUES (2,96);
INSERT INTO [dbo].[UserToTag] VALUES (7,96);
INSERT INTO [dbo].[UserToTag] VALUES (3,97);
INSERT INTO [dbo].[UserToTag] VALUES (10,97);
INSERT INTO [dbo].[UserToTag] VALUES (4,97);
INSERT INTO [dbo].[UserToTag] VALUES (10,98);
INSERT INTO [dbo].[UserToTag] VALUES (3,99);
INSERT INTO [dbo].[UserToTag] VALUES (10,99);
INSERT INTO [dbo].[UserToTag] VALUES (7,100);
INSERT INTO [dbo].[UserToTag] VALUES (9,100);
INSERT INTO [dbo].[UserToTag] VALUES (10,100);
INSERT INTO [dbo].[UserToTag] VALUES (5,100);
INSERT INTO [dbo].[UserToTag] VALUES (7,101);
INSERT INTO [dbo].[UserToTag] VALUES (10,101);
INSERT INTO [dbo].[UserToTag] VALUES (9,101);
INSERT INTO [dbo].[UserToTag] VALUES (4,101);
INSERT INTO [dbo].[UserToTag] VALUES (5,102);
INSERT INTO [dbo].[UserToTag] VALUES (3,102);
INSERT INTO [dbo].[UserToTag] VALUES (4,102);
INSERT INTO [dbo].[UserToTag] VALUES (6,103);
INSERT INTO [dbo].[UserToTag] VALUES (10,104);
INSERT INTO [dbo].[UserToTag] VALUES (2,104);
INSERT INTO [dbo].[UserToTag] VALUES (5,105);
INSERT INTO [dbo].[UserToTag] VALUES (8,105);
INSERT INTO [dbo].[UserToTag] VALUES (9,106);
INSERT INTO [dbo].[UserToTag] VALUES (1,107);
INSERT INTO [dbo].[UserToTag] VALUES (4,108);
INSERT INTO [dbo].[UserToTag] VALUES (10,108);
INSERT INTO [dbo].[UserToTag] VALUES (6,108);
INSERT INTO [dbo].[UserToTag] VALUES (8,108);
INSERT INTO [dbo].[UserToTag] VALUES (9,109);
INSERT INTO [dbo].[UserToTag] VALUES (5,109);
INSERT INTO [dbo].[UserToTag] VALUES (10,109);
INSERT INTO [dbo].[UserToTag] VALUES (7,109);
INSERT INTO [dbo].[UserToTag] VALUES (7,110);
INSERT INTO [dbo].[UserToTag] VALUES (10,110);
INSERT INTO [dbo].[UserToTag] VALUES (5,110);
INSERT INTO [dbo].[UserToTag] VALUES (4,110);
INSERT INTO [dbo].[UserToTag] VALUES (10,111);
INSERT INTO [dbo].[UserToTag] VALUES (6,111);
INSERT INTO [dbo].[UserToTag] VALUES (7,111);
INSERT INTO [dbo].[UserToTag] VALUES (2,112);
INSERT INTO [dbo].[UserToTag] VALUES (5,113);
INSERT INTO [dbo].[UserToTag] VALUES (6,113);
INSERT INTO [dbo].[UserToTag] VALUES (8,113);
INSERT INTO [dbo].[UserToTag] VALUES (2,113);
INSERT INTO [dbo].[UserToTag] VALUES (6,114);
INSERT INTO [dbo].[UserToTag] VALUES (9,114);
INSERT INTO [dbo].[UserToTag] VALUES (2,114);
INSERT INTO [dbo].[UserToTag] VALUES (3,114);
INSERT INTO [dbo].[UserToTag] VALUES (6,115);
INSERT INTO [dbo].[UserToTag] VALUES (5,115);
INSERT INTO [dbo].[UserToTag] VALUES (7,115);
INSERT INTO [dbo].[UserToTag] VALUES (5,116);
INSERT INTO [dbo].[UserToTag] VALUES (1,117);
INSERT INTO [dbo].[UserToTag] VALUES (4,117);
INSERT INTO [dbo].[UserToTag] VALUES (9,117);
INSERT INTO [dbo].[UserToTag] VALUES (10,118);
INSERT INTO [dbo].[UserToTag] VALUES (9,118);
INSERT INTO [dbo].[UserToTag] VALUES (2,118);
INSERT INTO [dbo].[UserToTag] VALUES (3,119);
INSERT INTO [dbo].[UserToTag] VALUES (8,119);
INSERT INTO [dbo].[UserToTag] VALUES (4,120);
INSERT INTO [dbo].[UserToTag] VALUES (8,120);
INSERT INTO [dbo].[UserToTag] VALUES (2,120);
INSERT INTO [dbo].[UserToTag] VALUES (10,120);
INSERT INTO [dbo].[UserToTag] VALUES (4,121);
INSERT INTO [dbo].[UserToTag] VALUES (7,121);
INSERT INTO [dbo].[UserToTag] VALUES (7,122);
INSERT INTO [dbo].[UserToTag] VALUES (4,122);
INSERT INTO [dbo].[UserToTag] VALUES (6,122);
INSERT INTO [dbo].[UserToTag] VALUES (1,122);
INSERT INTO [dbo].[UserToTag] VALUES (2,123);
INSERT INTO [dbo].[UserToTag] VALUES (6,123);
INSERT INTO [dbo].[UserToTag] VALUES (3,123);
INSERT INTO [dbo].[UserToTag] VALUES (1,123);
INSERT INTO [dbo].[UserToTag] VALUES (5,124);
INSERT INTO [dbo].[UserToTag] VALUES (4,124);
INSERT INTO [dbo].[UserToTag] VALUES (8,124);
INSERT INTO [dbo].[UserToTag] VALUES (7,124);
INSERT INTO [dbo].[UserToTag] VALUES (9,125);
INSERT INTO [dbo].[UserToTag] VALUES (3,125);
INSERT INTO [dbo].[UserToTag] VALUES (5,126);
INSERT INTO [dbo].[UserToTag] VALUES (3,126);
INSERT INTO [dbo].[UserToTag] VALUES (2,126);
INSERT INTO [dbo].[UserToTag] VALUES (8,127);
INSERT INTO [dbo].[UserToTag] VALUES (9,127);
INSERT INTO [dbo].[UserToTag] VALUES (4,127);
INSERT INTO [dbo].[UserToTag] VALUES (3,127);
INSERT INTO [dbo].[UserToTag] VALUES (2,128);
INSERT INTO [dbo].[UserToTag] VALUES (4,128);
INSERT INTO [dbo].[UserToTag] VALUES (10,128);
INSERT INTO [dbo].[UserToTag] VALUES (9,128);
INSERT INTO [dbo].[UserToTag] VALUES (9,129);
INSERT INTO [dbo].[UserToTag] VALUES (6,129);
INSERT INTO [dbo].[UserToTag] VALUES (3,130);
INSERT INTO [dbo].[UserToTag] VALUES (4,130);
INSERT INTO [dbo].[UserToTag] VALUES (6,130);
INSERT INTO [dbo].[UserToTag] VALUES (4,131);
INSERT INTO [dbo].[UserToTag] VALUES (9,131);
INSERT INTO [dbo].[UserToTag] VALUES (3,131);
INSERT INTO [dbo].[UserToTag] VALUES (5,132);
INSERT INTO [dbo].[UserToTag] VALUES (1,132);
INSERT INTO [dbo].[UserToTag] VALUES (2,132);
INSERT INTO [dbo].[UserToTag] VALUES (3,132);
INSERT INTO [dbo].[UserToTag] VALUES (1,133);
INSERT INTO [dbo].[UserToTag] VALUES (5,133);
INSERT INTO [dbo].[UserToTag] VALUES (3,133);
INSERT INTO [dbo].[UserToTag] VALUES (10,133);
INSERT INTO [dbo].[UserToTag] VALUES (5,134);
INSERT INTO [dbo].[UserToTag] VALUES (10,134);
INSERT INTO [dbo].[UserToTag] VALUES (4,134);
INSERT INTO [dbo].[UserToTag] VALUES (4,135);
INSERT INTO [dbo].[UserToTag] VALUES (5,136);
INSERT INTO [dbo].[UserToTag] VALUES (4,136);
INSERT INTO [dbo].[UserToTag] VALUES (9,136);
INSERT INTO [dbo].[UserToTag] VALUES (7,136);
INSERT INTO [dbo].[UserToTag] VALUES (4,137);
INSERT INTO [dbo].[UserToTag] VALUES (8,137);
INSERT INTO [dbo].[UserToTag] VALUES (5,137);
INSERT INTO [dbo].[UserToTag] VALUES (4,138);
INSERT INTO [dbo].[UserToTag] VALUES (9,139);
INSERT INTO [dbo].[UserToTag] VALUES (2,140);
INSERT INTO [dbo].[UserToTag] VALUES (10,140);
INSERT INTO [dbo].[UserToTag] VALUES (6,141);
INSERT INTO [dbo].[UserToTag] VALUES (3,141);
INSERT INTO [dbo].[UserToTag] VALUES (2,142);
INSERT INTO [dbo].[UserToTag] VALUES (3,142);
INSERT INTO [dbo].[UserToTag] VALUES (6,142);
INSERT INTO [dbo].[UserToTag] VALUES (7,143);
INSERT INTO [dbo].[UserToTag] VALUES (9,143);
INSERT INTO [dbo].[UserToTag] VALUES (8,144);
INSERT INTO [dbo].[UserToTag] VALUES (3,145);
INSERT INTO [dbo].[UserToTag] VALUES (6,145);
INSERT INTO [dbo].[UserToTag] VALUES (1,146);
INSERT INTO [dbo].[UserToTag] VALUES (10,146);
INSERT INTO [dbo].[UserToTag] VALUES (7,146);
INSERT INTO [dbo].[UserToTag] VALUES (8,147);
INSERT INTO [dbo].[UserToTag] VALUES (7,147);
INSERT INTO [dbo].[UserToTag] VALUES (9,147);
INSERT INTO [dbo].[UserToTag] VALUES (10,147);
INSERT INTO [dbo].[UserToTag] VALUES (5,148);
INSERT INTO [dbo].[UserToTag] VALUES (10,148);
INSERT INTO [dbo].[UserToTag] VALUES (6,148);
INSERT INTO [dbo].[UserToTag] VALUES (3,149);
INSERT INTO [dbo].[UserToTag] VALUES (4,149);
INSERT INTO [dbo].[UserToTag] VALUES (9,149);
INSERT INTO [dbo].[UserToTag] VALUES (10,149);
INSERT INTO [dbo].[UserToTag] VALUES (9,150);
INSERT INTO [dbo].[UserToTag] VALUES (4,150);
INSERT INTO [dbo].[UserToTag] VALUES (5,150);
INSERT INTO [dbo].[UserToTag] VALUES (2,150);
INSERT INTO [dbo].[UserToTag] VALUES (7,151);
INSERT INTO [dbo].[UserToTag] VALUES (9,151);
INSERT INTO [dbo].[UserToTag] VALUES (4,151);
INSERT INTO [dbo].[UserToTag] VALUES (10,151);
INSERT INTO [dbo].[UserToTag] VALUES (6,152);
INSERT INTO [dbo].[UserToTag] VALUES (4,153);
INSERT INTO [dbo].[UserToTag] VALUES (6,153);
INSERT INTO [dbo].[UserToTag] VALUES (2,153);
INSERT INTO [dbo].[UserToTag] VALUES (5,153);
INSERT INTO [dbo].[UserToTag] VALUES (2,154);
INSERT INTO [dbo].[UserToTag] VALUES (9,154);
INSERT INTO [dbo].[UserToTag] VALUES (4,154);
INSERT INTO [dbo].[UserToTag] VALUES (9,155);
INSERT INTO [dbo].[UserToTag] VALUES (2,155);
INSERT INTO [dbo].[UserToTag] VALUES (10,155);
INSERT INTO [dbo].[UserToTag] VALUES (9,156);
INSERT INTO [dbo].[UserToTag] VALUES (2,156);
INSERT INTO [dbo].[UserToTag] VALUES (10,156);
INSERT INTO [dbo].[UserToTag] VALUES (3,156);
INSERT INTO [dbo].[UserToTag] VALUES (6,157);
INSERT INTO [dbo].[UserToTag] VALUES (10,157);
INSERT INTO [dbo].[UserToTag] VALUES (5,157);
INSERT INTO [dbo].[UserToTag] VALUES (8,158);
INSERT INTO [dbo].[UserToTag] VALUES (4,159);
INSERT INTO [dbo].[UserToTag] VALUES (5,159);
INSERT INTO [dbo].[UserToTag] VALUES (6,159);
INSERT INTO [dbo].[UserToTag] VALUES (1,159);
INSERT INTO [dbo].[UserToTag] VALUES (10,160);
INSERT INTO [dbo].[UserToTag] VALUES (7,160);
INSERT INTO [dbo].[UserToTag] VALUES (5,160);
INSERT INTO [dbo].[UserToTag] VALUES (7,161);
INSERT INTO [dbo].[UserToTag] VALUES (5,162);
INSERT INTO [dbo].[UserToTag] VALUES (2,162);
INSERT INTO [dbo].[UserToTag] VALUES (9,163);
INSERT INTO [dbo].[UserToTag] VALUES (3,163);
INSERT INTO [dbo].[UserToTag] VALUES (10,163);
INSERT INTO [dbo].[UserToTag] VALUES (10,164);
INSERT INTO [dbo].[UserToTag] VALUES (9,164);
INSERT INTO [dbo].[UserToTag] VALUES (4,165);
INSERT INTO [dbo].[UserToTag] VALUES (7,165);
INSERT INTO [dbo].[UserToTag] VALUES (8,166);
INSERT INTO [dbo].[UserToTag] VALUES (4,166);
INSERT INTO [dbo].[UserToTag] VALUES (6,166);
INSERT INTO [dbo].[UserToTag] VALUES (4,167);
INSERT INTO [dbo].[UserToTag] VALUES (7,167);
INSERT INTO [dbo].[UserToTag] VALUES (3,168);
INSERT INTO [dbo].[UserToTag] VALUES (6,169);
INSERT INTO [dbo].[UserToTag] VALUES (2,169);
INSERT INTO [dbo].[UserToTag] VALUES (3,169);
INSERT INTO [dbo].[UserToTag] VALUES (7,170);
INSERT INTO [dbo].[UserToTag] VALUES (2,170);
INSERT INTO [dbo].[UserToTag] VALUES (8,170);
INSERT INTO [dbo].[UserToTag] VALUES (1,171);
INSERT INTO [dbo].[UserToTag] VALUES (10,171);
INSERT INTO [dbo].[UserToTag] VALUES (6,171);
INSERT INTO [dbo].[UserToTag] VALUES (6,172);
INSERT INTO [dbo].[UserToTag] VALUES (3,172);
INSERT INTO [dbo].[UserToTag] VALUES (5,172);
INSERT INTO [dbo].[UserToTag] VALUES (1,173);
INSERT INTO [dbo].[UserToTag] VALUES (9,173);
INSERT INTO [dbo].[UserToTag] VALUES (5,174);
INSERT INTO [dbo].[UserToTag] VALUES (10,174);
INSERT INTO [dbo].[UserToTag] VALUES (7,174);
INSERT INTO [dbo].[UserToTag] VALUES (4,174);
INSERT INTO [dbo].[UserToTag] VALUES (9,175);
INSERT INTO [dbo].[UserToTag] VALUES (5,175);
INSERT INTO [dbo].[UserToTag] VALUES (10,176);
INSERT INTO [dbo].[UserToTag] VALUES (6,176);
INSERT INTO [dbo].[UserToTag] VALUES (4,176);
INSERT INTO [dbo].[UserToTag] VALUES (8,177);
INSERT INTO [dbo].[UserToTag] VALUES (4,177);
INSERT INTO [dbo].[UserToTag] VALUES (1,177);
INSERT INTO [dbo].[UserToTag] VALUES (7,178);
INSERT INTO [dbo].[UserToTag] VALUES (1,178);
INSERT INTO [dbo].[UserToTag] VALUES (3,178);
INSERT INTO [dbo].[UserToTag] VALUES (4,178);
INSERT INTO [dbo].[UserToTag] VALUES (10,179);
INSERT INTO [dbo].[UserToTag] VALUES (2,179);
INSERT INTO [dbo].[UserToTag] VALUES (7,180);
INSERT INTO [dbo].[UserToTag] VALUES (6,180);
INSERT INTO [dbo].[UserToTag] VALUES (8,180);
INSERT INTO [dbo].[UserToTag] VALUES (1,180);
INSERT INTO [dbo].[UserToTag] VALUES (5,181);
INSERT INTO [dbo].[UserToTag] VALUES (9,181);
INSERT INTO [dbo].[UserToTag] VALUES (10,181);
INSERT INTO [dbo].[UserToTag] VALUES (8,182);
INSERT INTO [dbo].[UserToTag] VALUES (7,182);
INSERT INTO [dbo].[UserToTag] VALUES (1,183);
INSERT INTO [dbo].[UserToTag] VALUES (5,183);
INSERT INTO [dbo].[UserToTag] VALUES (4,183);
INSERT INTO [dbo].[UserToTag] VALUES (2,183);
INSERT INTO [dbo].[UserToTag] VALUES (10,184);
INSERT INTO [dbo].[UserToTag] VALUES (3,184);
INSERT INTO [dbo].[UserToTag] VALUES (1,185);
INSERT INTO [dbo].[UserToTag] VALUES (6,185);
INSERT INTO [dbo].[UserToTag] VALUES (7,185);
INSERT INTO [dbo].[UserToTag] VALUES (2,185);
INSERT INTO [dbo].[UserToTag] VALUES (6,186);
INSERT INTO [dbo].[UserToTag] VALUES (1,186);
INSERT INTO [dbo].[UserToTag] VALUES (9,187);
INSERT INTO [dbo].[UserToTag] VALUES (5,188);
INSERT INTO [dbo].[UserToTag] VALUES (3,189);
INSERT INTO [dbo].[UserToTag] VALUES (2,190);
INSERT INTO [dbo].[UserToTag] VALUES (10,191);
INSERT INTO [dbo].[UserToTag] VALUES (6,191);
INSERT INTO [dbo].[UserToTag] VALUES (2,192);
INSERT INTO [dbo].[UserToTag] VALUES (3,192);
INSERT INTO [dbo].[UserToTag] VALUES (10,193);
INSERT INTO [dbo].[UserToTag] VALUES (1,193);
INSERT INTO [dbo].[UserToTag] VALUES (8,194);
INSERT INTO [dbo].[UserToTag] VALUES (7,194);
INSERT INTO [dbo].[UserToTag] VALUES (10,195);
INSERT INTO [dbo].[UserToTag] VALUES (9,196);
INSERT INTO [dbo].[UserToTag] VALUES (9,197);
INSERT INTO [dbo].[UserToTag] VALUES (9,198);
INSERT INTO [dbo].[UserToTag] VALUES (2,198);
INSERT INTO [dbo].[UserToTag] VALUES (10,198);
INSERT INTO [dbo].[UserToTag] VALUES (1,198);
INSERT INTO [dbo].[UserToTag] VALUES (10,199);
INSERT INTO [dbo].[UserToTag] VALUES (8,199);
INSERT INTO [dbo].[UserToTag] VALUES (4,199);
INSERT INTO [dbo].[UserToTag] VALUES (5,199);
INSERT INTO [dbo].[UserToTag] VALUES (2,200);
INSERT INTO [dbo].[UserToTag] VALUES (4,200);
INSERT INTO [dbo].[UserToTag] VALUES (5,200);
