use liveart_dg;

CREATE TABLE ProductName (
    Value varchar(30) NOT NULL
);

INSERT INTO ProductName VALUES ('Mulberry Silk');
INSERT INTO ProductName VALUES ('Chelsea Mauve');
INSERT INTO ProductName VALUES ('Cabbage Rose');
INSERT INTO ProductName VALUES ('Rose Brocade');
INSERT INTO ProductName VALUES ('Deepest Mauve');
INSERT INTO ProductName VALUES ('Toile Red');
INSERT INTO ProductName VALUES ('Decorous Amber');
INSERT INTO ProductName VALUES ('Cajun Red');
INSERT INTO ProductName VALUES ('Eastlake Gold');
INSERT INTO ProductName VALUES ('Wickerwork');
INSERT INTO ProductName VALUES ('Crewel Tan');
INSERT INTO ProductName VALUES ('Empire Gold');
INSERT INTO ProductName VALUES ('Majolica Green');
INSERT INTO ProductName VALUES ('Sheraton Sage');
INSERT INTO ProductName VALUES ('Gallery Green');
INSERT INTO ProductName VALUES ('Billiard Green');
INSERT INTO ProductName VALUES ('Calico');
INSERT INTO ProductName VALUES ('Teal Stencil');
INSERT INTO ProductName VALUES ('Festoon Aqua');
INSERT INTO ProductName VALUES ('Peacock Plume');
INSERT INTO ProductName VALUES ('Queen Anne Lilac');
INSERT INTO ProductName VALUES ('Patchwork Plum');
INSERT INTO ProductName VALUES ('Pewter Tankard');
INSERT INTO ProductName VALUES ('Curio Gray');
INSERT INTO ProductName VALUES ('Rosedust');
INSERT INTO ProductName VALUES ('Rachel Pink');
INSERT INTO ProductName VALUES ('Aristocrat Peach');
INSERT INTO ProductName VALUES ('Caen Stone');
INSERT INTO ProductName VALUES ('Acanthus');
INSERT INTO ProductName VALUES ('Colonial Yellow');
INSERT INTO ProductName VALUES ('Dutch Tile Blue');
INSERT INTO ProductName VALUES ('Needlepoint Navy');
INSERT INTO ProductName VALUES ('Rembrandt Ruby');
INSERT INTO ProductName VALUES ('Roycroft Rose');
INSERT INTO ProductName VALUES ('Indian White');
INSERT INTO ProductName VALUES ('Buckram Binding');
INSERT INTO ProductName VALUES ('Morris Room Grey');
INSERT INTO ProductName VALUES ('Library Pewter');
INSERT INTO ProductName VALUES ('Portrait Tone');
INSERT INTO ProductName VALUES ('Roycroft Adobe');
INSERT INTO ProductName VALUES ('Dard Hunter Green');
INSERT INTO ProductName VALUES ('Ruskin Room Green');
INSERT INTO ProductName VALUES ('Peristyle Brass');
INSERT INTO ProductName VALUES ('Hubbard Squash');
INSERT INTO ProductName VALUES ('Antiquarian Brown');
INSERT INTO ProductName VALUES ('White Hyacinth');
INSERT INTO ProductName VALUES ('Studio Blue Green');
INSERT INTO ProductName VALUES ('Bunglehouse Blue');
INSERT INTO ProductName VALUES ('Silver Gray');
INSERT INTO ProductName VALUES ('Classic Light Buff');
INSERT INTO ProductName VALUES ('Classic Ivory');
INSERT INTO ProductName VALUES ('Pearl Gray');
INSERT INTO ProductName VALUES ('Porcelain');
INSERT INTO ProductName VALUES ('Twilight Gray');
INSERT INTO ProductName VALUES ('Light French Gray');
INSERT INTO ProductName VALUES ('Classic Sand');
INSERT INTO ProductName VALUES ('Chinese Red');
INSERT INTO ProductName VALUES ('Jazz Age Coral');
INSERT INTO ProductName VALUES ('Frostwork');
INSERT INTO ProductName VALUES ('Alexandrite');
INSERT INTO ProductName VALUES ('Salon Rose');
INSERT INTO ProductName VALUES ('Studio Mauve');
INSERT INTO ProductName VALUES ('Blue Sky');
INSERT INTO ProductName VALUES ('Blue Peacock');
INSERT INTO ProductName VALUES ('Vogue Green');
INSERT INTO ProductName VALUES ('Cascade Green');
INSERT INTO ProductName VALUES ('Belvedere Cream');
INSERT INTO ProductName VALUES ('Copen Blue');
INSERT INTO ProductName VALUES ('Rose Tan');
INSERT INTO ProductName VALUES ('Pink Shadow');
INSERT INTO ProductName VALUES ('Orchid');
INSERT INTO ProductName VALUES ('Deep Maroon');
INSERT INTO ProductName VALUES ('Chartreuse');
INSERT INTO ProductName VALUES ('Radiant Lilac');
INSERT INTO ProductName VALUES ('Holiday Turquoise');
INSERT INTO ProductName VALUES ('Appleblossom');
INSERT INTO ProductName VALUES ('Classic French Gray');
INSERT INTO ProductName VALUES ('Sunbeam Yellow');
INSERT INTO ProductName VALUES ('Pinky Beige');
INSERT INTO ProductName VALUES ('Pink Flamingo');
INSERT INTO ProductName VALUES ('Rookwood Dark Red');
INSERT INTO ProductName VALUES ('Rookwood Red');
INSERT INTO ProductName VALUES ('Rookwood Terra Cotta');
INSERT INTO ProductName VALUES ('Renwick Rose Beige');
INSERT INTO ProductName VALUES ('Renwick Beige');
INSERT INTO ProductName VALUES ('Rookwood Brown');
INSERT INTO ProductName VALUES ('Rookwood Medium Brown');
INSERT INTO ProductName VALUES ('Rookwood Dark Brown');
INSERT INTO ProductName VALUES ('Rookwood Shutter Green');
INSERT INTO ProductName VALUES ('Rookwood Sash Green');
INSERT INTO ProductName VALUES ('Rookwood Blue Green');
INSERT INTO ProductName VALUES ('Rookwood Jade');
INSERT INTO ProductName VALUES ('Downing Straw');
INSERT INTO ProductName VALUES ('Rookwood Antique Gold');
INSERT INTO ProductName VALUES ('Renwick Olive');
INSERT INTO ProductName VALUES ('Rookwood Dark Green');
INSERT INTO ProductName VALUES ('Rookwood Amber');
INSERT INTO ProductName VALUES ('Renwick Heather');
INSERT INTO ProductName VALUES ('Downing Slate');
INSERT INTO ProductName VALUES ('Downing Earth');
INSERT INTO ProductName VALUES ('Downing Stone');
INSERT INTO ProductName VALUES ('Downing Sand');
INSERT INTO ProductName VALUES ('Rookwood Clay');
INSERT INTO ProductName VALUES ('Renwick Golden Oak');
INSERT INTO ProductName VALUES ('Colonial Revival Sea Green');
INSERT INTO ProductName VALUES ('Colonial Revival Green Stone');
INSERT INTO ProductName VALUES ('Colonial Revival Stone');
INSERT INTO ProductName VALUES ('Colonial Revival Tan');
INSERT INTO ProductName VALUES ('Classical White');
INSERT INTO ProductName VALUES ('Classical Gold');
INSERT INTO ProductName VALUES ('Colonial Revival Gray');
INSERT INTO ProductName VALUES ('Roycroft Vellum');
INSERT INTO ProductName VALUES ('Birdseye Maple');
INSERT INTO ProductName VALUES ('Craftsman Brown');
INSERT INTO ProductName VALUES ('Quartersawn Oak');
INSERT INTO ProductName VALUES ('Aurora Brown');
INSERT INTO ProductName VALUES ('Polished Mahogany');
INSERT INTO ProductName VALUES ('Roycroft Copper Red');
INSERT INTO ProductName VALUES ('Hammered Silver');
INSERT INTO ProductName VALUES ('Weathered Shingle');
INSERT INTO ProductName VALUES ('Roycroft Suede');
INSERT INTO ProductName VALUES ('Roycroft Brass');
INSERT INTO ProductName VALUES ('Roycroft Mist Gray');
INSERT INTO ProductName VALUES ('Bunglehouse Gray');
INSERT INTO ProductName VALUES ('Roycroft Bronze Green');
INSERT INTO ProductName VALUES ('Roycroft Bottle Green');
INSERT INTO ProductName VALUES ('Roycroft Pewter');
INSERT INTO ProductName VALUES ('Westchester Gray');
INSERT INTO ProductName VALUES ('Chelsea Gray');
INSERT INTO ProductName VALUES ('Sage Green Light');
INSERT INTO ProductName VALUES ('Plymouth Green');
INSERT INTO ProductName VALUES ('New Colonial Yellow');
INSERT INTO ProductName VALUES ('Caribbean Coral');
INSERT INTO ProductName VALUES ('Sycamore Tan');
INSERT INTO ProductName VALUES ('Fairfax Brown');
INSERT INTO ProductName VALUES ('Peace Yellow');
INSERT INTO ProductName VALUES ('Harvest Gold');
INSERT INTO ProductName VALUES ('Beige');
INSERT INTO ProductName VALUES ('Sage');
INSERT INTO ProductName VALUES ('Avocado');
INSERT INTO ProductName VALUES ('Burma Jade');
INSERT INTO ProductName VALUES ('Powder Blue');
INSERT INTO ProductName VALUES ('Stratford Blue');
INSERT INTO ProductName VALUES ('Classic Yellow');
INSERT INTO ProductName VALUES ('Wine Country');
INSERT INTO ProductName VALUES ('Elderberry');
INSERT INTO ProductName VALUES ('Pomegranate');
INSERT INTO ProductName VALUES ('Poppy Flower');
INSERT INTO ProductName VALUES ('Carmine');
INSERT INTO ProductName VALUES ('Crimson Red');
INSERT INTO ProductName VALUES ('Scarlet');
INSERT INTO ProductName VALUES ('Cardinal');
INSERT INTO ProductName VALUES ('Redwing');
INSERT INTO ProductName VALUES ('Primary Red');
INSERT INTO ProductName VALUES ('Pompeii Red');
INSERT INTO ProductName VALUES ('Chanticleer');
INSERT INTO ProductName VALUES ('Classy Red');
INSERT INTO ProductName VALUES ('Vermilion');
INSERT INTO ProductName VALUES ('Red Prairie');
INSERT INTO ProductName VALUES ('Clay Pot');
INSERT INTO ProductName VALUES ('Bramble Bush');
INSERT INTO ProductName VALUES ('Woodsy Brown');
INSERT INTO ProductName VALUES ('Iron Gate');
INSERT INTO ProductName VALUES ('W eathervane');
INSERT INTO ProductName VALUES ('Garden Path');
INSERT INTO ProductName VALUES ('Marsh Fern');
INSERT INTO ProductName VALUES ('Black Emerald');
INSERT INTO ProductName VALUES ('Snowfall');
INSERT INTO ProductName VALUES ('Grayish');
INSERT INTO ProductName VALUES ('Essential Gray');
INSERT INTO ProductName VALUES ('Proper Gray');
INSERT INTO ProductName VALUES ('Mink');
INSERT INTO ProductName VALUES ('Folkstone');
INSERT INTO ProductName VALUES ('Black Bean');
INSERT INTO ProductName VALUES ('Smart White');
INSERT INTO ProductName VALUES ('Individual White');
INSERT INTO ProductName VALUES ('Imagine');
INSERT INTO ProductName VALUES ('Flexible Gray');
INSERT INTO ProductName VALUES ('Chinchilla');
INSERT INTO ProductName VALUES ('Browse Brown');
INSERT INTO ProductName VALUES ('Bitter Chocolate');
INSERT INTO ProductName VALUES ('Quartz White');
INSERT INTO ProductName VALUES ('Vaguely Mauve');
INSERT INTO ProductName VALUES ('Chaise Mauve');
INSERT INTO ProductName VALUES ('Intuitive');
INSERT INTO ProductName VALUES ('Enigma');
INSERT INTO ProductName VALUES ('Poetry Plum');
INSERT INTO ProductName VALUES ('Marooned');
INSERT INTO ProductName VALUES ('Dreamy White');
INSERT INTO ProductName VALUES ('Breathless');
INSERT INTO ProductName VALUES ('Insightful Rose');
INSERT INTO ProductName VALUES ('Dressy Rose');
INSERT INTO ProductName VALUES ('Socialite');
INSERT INTO ProductName VALUES ('River Rouge');
INSERT INTO ProductName VALUES ('Cordovan');
INSERT INTO ProductName VALUES ('Cultured Pearl');
INSERT INTO ProductName VALUES ('White Truffle');
INSERT INTO ProductName VALUES ('Artistic Taupe');
INSERT INTO ProductName VALUES ('Glamour');
INSERT INTO ProductName VALUES ('Dutch Cocoa');
INSERT INTO ProductName VALUES ('Bateau Brown');
INSERT INTO ProductName VALUES ('Arresting Auburn');
INSERT INTO ProductName VALUES ('Gauzy White');
INSERT INTO ProductName VALUES ('Angora');
INSERT INTO ProductName VALUES ('Temperate Taupe');
INSERT INTO ProductName VALUES ('Truly Taupe');
INSERT INTO ProductName VALUES ('Poised Taupe');
INSERT INTO ProductName VALUES ('Less Brown');
INSERT INTO ProductName VALUES ('Otter');
INSERT INTO ProductName VALUES ('Hush White');
INSERT INTO ProductName VALUES ('Unfussy Beige');
INSERT INTO ProductName VALUES ('Doeskin');
INSERT INTO ProductName VALUES ('Emerging Taupe');
INSERT INTO ProductName VALUES ('Swing Brown');
INSERT INTO ProductName VALUES ('Hot Cocoa');
INSERT INTO ProductName VALUES ('Terra Brun');
INSERT INTO ProductName VALUES ('Gorgeous White');
INSERT INTO ProductName VALUES ('Abalone Shell');
INSERT INTO ProductName VALUES ('Sashay Sand');
INSERT INTO ProductName VALUES ('Sandbank');
INSERT INTO ProductName VALUES ('Reddened Earth');
INSERT INTO ProductName VALUES ('Canyon Clay');
INSERT INTO ProductName VALUES ('Fiery Brown');
INSERT INTO ProductName VALUES ('Polite White');
INSERT INTO ProductName VALUES ('Malted Milk');
INSERT INTO ProductName VALUES ('Likeable Sand');
INSERT INTO ProductName VALUES ('Interface Tan');
INSERT INTO ProductName VALUES ('Moroccan Brown');
INSERT INTO ProductName VALUES ('T anbark');
INSERT INTO ProductName VALUES ('Rugged Brown');
INSERT INTO ProductName VALUES ('Nice White');
INSERT INTO ProductName VALUES ('Reticence');
INSERT INTO ProductName VALUES ('Bona Fide Beige');
INSERT INTO ProductName VALUES ('Sand Trap');
INSERT INTO ProductName VALUES ('Mocha');
INSERT INTO ProductName VALUES ('Brevity Brown');
INSERT INTO ProductName VALUES ('French Roast');
INSERT INTO ProductName VALUES ('Heron Plume');
INSERT INTO ProductName VALUES ('Popular Gray');
INSERT INTO ProductName VALUES ('Versatile Gray');
INSERT INTO ProductName VALUES ('Perfect Greige');
INSERT INTO ProductName VALUES ('Spalding Gray');
INSERT INTO ProductName VALUES ('Garret Gray');
INSERT INTO ProductName VALUES ('Turkish Coffee');
INSERT INTO ProductName VALUES ('Everyday White');
INSERT INTO ProductName VALUES ('Realist Beige');
INSERT INTO ProductName VALUES ('Diverse Beige');
INSERT INTO ProductName VALUES ('Utterly Beige');
INSERT INTO ProductName VALUES ('Down Home');
INSERT INTO ProductName VALUES ('Cobble Brown');
INSERT INTO ProductName VALUES ('Sable');
INSERT INTO ProductName VALUES ('Modest White');
INSERT INTO ProductName VALUES ('Simplify Beige');
INSERT INTO ProductName VALUES ('Sand Dune');
INSERT INTO ProductName VALUES ('Trusty Tan');
INSERT INTO ProductName VALUES ('Nuthatch');
INSERT INTO ProductName VALUES ('Grounded');
INSERT INTO ProductName VALUES ('Java');
INSERT INTO ProductName VALUES ('Reliable White');
INSERT INTO ProductName VALUES ('Lightweight Beige');
INSERT INTO ProductName VALUES ('Familiar Beige');
INSERT INTO ProductName VALUES ('Sensational Sand');
INSERT INTO ProductName VALUES ('T oasty');
INSERT INTO ProductName VALUES ('Jute Brown');
INSERT INTO ProductName VALUES ('Sturdy Brown');
INSERT INTO ProductName VALUES ('Pacer White');
INSERT INTO ProductName VALUES ('Sand Dollar');
INSERT INTO ProductName VALUES ('Practical Beige');
INSERT INTO ProductName VALUES ('Sands Of Time');
INSERT INTO ProductName VALUES ('Portabello');
INSERT INTO ProductName VALUES ('Tea Chest');
INSERT INTO ProductName VALUES ('Kaffee');
INSERT INTO ProductName VALUES ('Divine White');
INSERT INTO ProductName VALUES ('Kilim Beige');
INSERT INTO ProductName VALUES ('Nomadic Desert');
INSERT INTO ProductName VALUES ('Latte');
INSERT INTO ProductName VALUES ('Hopsack');
INSERT INTO ProductName VALUES ('Steady Brown');
INSERT INTO ProductName VALUES ('Coconut Husk');
INSERT INTO ProductName VALUES ('Biscuit');
INSERT INTO ProductName VALUES ('Interactive Cream');
INSERT INTO ProductName VALUES ('Bagel');
INSERT INTO ProductName VALUES ('Totally Tan');
INSERT INTO ProductName VALUES ('Tatami Tan');
INSERT INTO ProductName VALUES ('Smokey Topaz');
INSERT INTO ProductName VALUES ('Leather Bound');
INSERT INTO ProductName VALUES ('Antique White');
INSERT INTO ProductName VALUES ('Believable Buff');
INSERT INTO ProductName VALUES ('Whole Wheat');
INSERT INTO ProductName VALUES ('Camelback');
INSERT INTO ProductName VALUES ('Baguette');
INSERT INTO ProductName VALUES ('Cardboard');
INSERT INTO ProductName VALUES ('Craft Paper');
INSERT INTO ProductName VALUES ('Navajo White');
INSERT INTO ProductName VALUES ('Ivoire');
INSERT INTO ProductName VALUES ('Blonde');
INSERT INTO ProductName VALUES ('Restrained Gold');
INSERT INTO ProductName VALUES ('Mannered Gold');
INSERT INTO ProductName VALUES ('Chamois');
INSERT INTO ProductName VALUES ('Relic Bronze');
INSERT INTO ProductName VALUES ('Muslin');
INSERT INTO ProductName VALUES ('Netsuke');
INSERT INTO ProductName VALUES ('Ecru');
INSERT INTO ProductName VALUES ('Harmonic Tan');
INSERT INTO ProductName VALUES ('Burlap');
INSERT INTO ProductName VALUES ('Artifact');
INSERT INTO ProductName VALUES ('Mossy Gold');
INSERT INTO ProductName VALUES ('Moderate White');
INSERT INTO ProductName VALUES ('Softer Tan');
INSERT INTO ProductName VALUES ('Macadamia');
INSERT INTO ProductName VALUES ('Basket Beige');
INSERT INTO ProductName VALUES ('Dapper Tan');
INSERT INTO ProductName VALUES ('Thatch Brown');
INSERT INTO ProductName VALUES ('Umber');
INSERT INTO ProductName VALUES ('Panda White');
INSERT INTO ProductName VALUES ('Wool Skein');
INSERT INTO ProductName VALUES ('Relaxed Khaki');
INSERT INTO ProductName VALUES ('Universal Khaki');
INSERT INTO ProductName VALUES ('Quiver Tan');
INSERT INTO ProductName VALUES ('Superior Bronze');
INSERT INTO ProductName VALUES ('Prot ̈¦g ̈¦ Bronze');
INSERT INTO ProductName VALUES ('Nacre');
INSERT INTO ProductName VALUES ('Rice Grain');
INSERT INTO ProductName VALUES ('Ramie');
INSERT INTO ProductName VALUES ('Favorite Tan');
INSERT INTO ProductName VALUES ('Sawdust');
INSERT INTO ProductName VALUES ('High Tea');
INSERT INTO ProductName VALUES ('Best Bronze');
INSERT INTO ProductName VALUES ('Nonchalant White');
INSERT INTO ProductName VALUES ('Ancient Marble');
INSERT INTO ProductName VALUES ('Grassland');
INSERT INTO ProductName VALUES ('Svelte Sage');
INSERT INTO ProductName VALUES ('Connected Gray');
INSERT INTO ProductName VALUES ('Eclipse');
INSERT INTO ProductName VALUES ('Garden Gate');
INSERT INTO ProductName VALUES ('Moderne White');
INSERT INTO ProductName VALUES ('Sedate Gray');
INSERT INTO ProductName VALUES ('Techno Gray');
INSERT INTO ProductName VALUES ('Chatroom');
INSERT INTO ProductName VALUES ('Hardware');
INSERT INTO ProductName VALUES ('Cocoon');
INSERT INTO ProductName VALUES ('Andiron');
INSERT INTO ProductName VALUES ('Sagey');
INSERT INTO ProductName VALUES ('Liveable Green');
INSERT INTO ProductName VALUES ('Softened Green');
INSERT INTO ProductName VALUES ('Clary Sage');
INSERT INTO ProductName VALUES ('Artichoke');
INSERT INTO ProductName VALUES ('Oakmoss');
INSERT INTO ProductName VALUES ('Secret Garden');
INSERT INTO ProductName VALUES ('Ethereal White');
INSERT INTO ProductName VALUES ('Conservative Gray');
INSERT INTO ProductName VALUES ('Austere Gray');
INSERT INTO ProductName VALUES ('Escape Gray');
INSERT INTO ProductName VALUES ('Dried Thyme');
INSERT INTO ProductName VALUES ('Rosemary');
INSERT INTO ProductName VALUES ('Shade-Grown');
INSERT INTO ProductName VALUES ('Opaline');
INSERT INTO ProductName VALUES ('Filmy Green');
INSERT INTO ProductName VALUES ('Contented');
INSERT INTO ProductName VALUES ('Coastal Plain');
INSERT INTO ProductName VALUES ('Privilege Green');
INSERT INTO ProductName VALUES ('Basil');
INSERT INTO ProductName VALUES ('Rock Garden');
INSERT INTO ProductName VALUES ('Frosty White');
INSERT INTO ProductName VALUES ('Aloof Gray');
INSERT INTO ProductName VALUES ('Sensible Hue');
INSERT INTO ProductName VALUES ('Rare Gray');
INSERT INTO ProductName VALUES ('Link Gray');
INSERT INTO ProductName VALUES ('Thunderous');
INSERT INTO ProductName VALUES ('Cast Iron');
INSERT INTO ProductName VALUES ('Spare White');
INSERT INTO ProductName VALUES ('Sea Salt');
INSERT INTO ProductName VALUES ('Comfort Gray');
INSERT INTO ProductName VALUES ('Oyster Bay');
INSERT INTO ProductName VALUES ('Retreat');
INSERT INTO ProductName VALUES ('Pewter Green');
INSERT INTO ProductName VALUES ('Ripe Olive');
INSERT INTO ProductName VALUES ('Window Pane');
INSERT INTO ProductName VALUES ('Rainwashed');
INSERT INTO ProductName VALUES ('Quietude');
INSERT INTO ProductName VALUES ('Halcyon Green');
INSERT INTO ProductName VALUES ('Underseas');
INSERT INTO ProductName VALUES ('Rocky River');
INSERT INTO ProductName VALUES ('Jasper');
INSERT INTO ProductName VALUES ('T opsail');
INSERT INTO ProductName VALUES ('Tradewind');
INSERT INTO ProductName VALUES ('Rain');
INSERT INTO ProductName VALUES ('Interesting Aqua');
INSERT INTO ProductName VALUES ('Moody Blue');
INSERT INTO ProductName VALUES ('Riverway');
INSERT INTO ProductName VALUES ('Still Water');
INSERT INTO ProductName VALUES ('Mountain Air');
INSERT INTO ProductName VALUES ('Sleepy Blue');
INSERT INTO ProductName VALUES ('Languid Blue');
INSERT INTO ProductName VALUES ('Meditative');
INSERT INTO ProductName VALUES ('Refuge');
INSERT INTO ProductName VALUES ('Tempe Star');
INSERT INTO ProductName VALUES ('Rainstorm');
INSERT INTO ProductName VALUES ('Rock Candy');
INSERT INTO ProductName VALUES ('Misty');
INSERT INTO ProductName VALUES ('Samovar Silver');
INSERT INTO ProductName VALUES ('Uncertain Gray');
INSERT INTO ProductName VALUES ('Foggy Day');
INSERT INTO ProductName VALUES ('Grays Harbor');
INSERT INTO ProductName VALUES ('Dark Night');
INSERT INTO ProductName VALUES ('Icicle');
INSERT INTO ProductName VALUES ('Upward');
INSERT INTO ProductName VALUES ('Windy Blue');
INSERT INTO ProductName VALUES ('Aleutian');
INSERT INTO ProductName VALUES ('Bracing Blue');
INSERT INTO ProductName VALUES ('Distance');
INSERT INTO ProductName VALUES ('Naval');
INSERT INTO ProductName VALUES ('Quicksilver');
INSERT INTO ProductName VALUES ('North Star');
INSERT INTO ProductName VALUES ('Krypton');
INSERT INTO ProductName VALUES ('Jubilee');
INSERT INTO ProductName VALUES ('Storm Cloud');
INSERT INTO ProductName VALUES ('Granite Peak');
INSERT INTO ProductName VALUES ('Outerspace');
INSERT INTO ProductName VALUES ('Ice Cube');
INSERT INTO ProductName VALUES ('Olympus White');
INSERT INTO ProductName VALUES ('Lazy Gray');
INSERT INTO ProductName VALUES ('Morning Fog');
INSERT INTO ProductName VALUES ('Serious Gray');
INSERT INTO ProductName VALUES ('Gibraltar');
INSERT INTO ProductName VALUES ('Tricorn Black');
INSERT INTO ProductName VALUES ('Spatial White');
INSERT INTO ProductName VALUES ('Unique Gray');
INSERT INTO ProductName VALUES ('Swanky Gray');
INSERT INTO ProductName VALUES ('Mysterious Mauve');
INSERT INTO ProductName VALUES ('Exclusive Plum');
INSERT INTO ProductName VALUES ('Midnight');
INSERT INTO ProductName VALUES ('Quixotic Plum');
INSERT INTO ProductName VALUES ('Discreet White');
INSERT INTO ProductName VALUES ('Sensitive Tint');
INSERT INTO ProductName VALUES ('Veiled Violet');
INSERT INTO ProductName VALUES ('Beguiling Mauve');
INSERT INTO ProductName VALUES ('Soulmate');
INSERT INTO ProductName VALUES ('Expressive Plum');
INSERT INTO ProductName VALUES ('Plum Brown');
INSERT INTO ProductName VALUES ('Nouvelle White');
INSERT INTO ProductName VALUES ('Destiny');
INSERT INTO ProductName VALUES ('Fashionable Gray');
INSERT INTO ProductName VALUES ('Mystical Shade');
INSERT INTO ProductName VALUES ('Special Gray');
INSERT INTO ProductName VALUES ('Cloak Gray');
INSERT INTO ProductName VALUES ('Black Swan');
INSERT INTO ProductName VALUES ('Mauve Tinge');
INSERT INTO ProductName VALUES ('W allflower');
INSERT INTO ProductName VALUES ('Mauve Finery');
INSERT INTO ProductName VALUES ('Thistle');
INSERT INTO ProductName VALUES ('Plum Dandy');
INSERT INTO ProductName VALUES ('Grape Harvest');
INSERT INTO ProductName VALUES ('Mature Grape');
INSERT INTO ProductName VALUES ('White Beet');
INSERT INTO ProductName VALUES ('Rosebud');
INSERT INTO ProductName VALUES ('Delightful');
INSERT INTO ProductName VALUES ('Ros ̈¦');
INSERT INTO ProductName VALUES ('Moss Rose');
INSERT INTO ProductName VALUES ('Berry Bush');
INSERT INTO ProductName VALUES ('Fabulous Grape');
INSERT INTO ProductName VALUES ('Rose Of Sharon');
INSERT INTO ProductName VALUES ('Demure');
INSERT INTO ProductName VALUES ('Fading Rose');
INSERT INTO ProductName VALUES ('Rose Embroidery');
INSERT INTO ProductName VALUES ('Concerto');
INSERT INTO ProductName VALUES ('Aged Wine');
INSERT INTO ProductName VALUES ('Burgundy');
INSERT INTO ProductName VALUES ('Patient White');
INSERT INTO ProductName VALUES ('Innocence');
INSERT INTO ProductName VALUES ('Rose Colored');
INSERT INTO ProductName VALUES ('Pressed Flower');
INSERT INTO ProductName VALUES ('Rambling Rose');
INSERT INTO ProductName VALUES ('Cordial');
INSERT INTO ProductName VALUES ('Fine Wine');
INSERT INTO ProductName VALUES ('Possibly Pink');
INSERT INTO ProductName VALUES ('Charming Pink');
INSERT INTO ProductName VALUES ('Lotus Flower');
INSERT INTO ProductName VALUES ('Memorable Rose');
INSERT INTO ProductName VALUES ('Redbud');
INSERT INTO ProductName VALUES ('Kirsch Red');
INSERT INTO ProductName VALUES ('Luxurious Red');
INSERT INTO ProductName VALUES ('White Dogwood');
INSERT INTO ProductName VALUES ('Rosy Outlook');
INSERT INTO ProductName VALUES ('Gracious Rose');
INSERT INTO ProductName VALUES ('Resounding Rose');
INSERT INTO ProductName VALUES ('Reddish');
INSERT INTO ProductName VALUES ('Bravado Red');
INSERT INTO ProductName VALUES ('Red Bay');
INSERT INTO ProductName VALUES ('Intimate White');
INSERT INTO ProductName VALUES ('Romance');
INSERT INTO ProductName VALUES ('Mellow Coral');
INSERT INTO ProductName VALUES ('Constant Coral');
INSERT INTO ProductName VALUES ('Henna Shade');
INSERT INTO ProductName VALUES ('Bold Brick');
INSERT INTO ProductName VALUES ('Fireweed');
INSERT INTO ProductName VALUES ('Faint Coral');
INSERT INTO ProductName VALUES ('Quaint Peche');
INSERT INTO ProductName VALUES ('Smoky Salmon');
INSERT INTO ProductName VALUES ('Coral Island');
INSERT INTO ProductName VALUES ('Foxy');
INSERT INTO ProductName VALUES ('Flower Pot');
INSERT INTO ProductName VALUES ('Fired Brick');
INSERT INTO ProductName VALUES ('Nearly Peach');
INSERT INTO ProductName VALUES ('Spun Sugar');
INSERT INTO ProductName VALUES ('Warming Peach');
INSERT INTO ProductName VALUES ('Persimmon');
INSERT INTO ProductName VALUES ('Baked Clay');
INSERT INTO ProductName VALUES ('Red Cent');
INSERT INTO ProductName VALUES ('Spicy Hue');
INSERT INTO ProductName VALUES ('Alluring White');
INSERT INTO ProductName VALUES ('Peach Fuzz');
INSERT INTO ProductName VALUES ('Sumptuous Peach');
INSERT INTO ProductName VALUES ('Fame Orange');
INSERT INTO ProductName VALUES ('Chrysanthemum');
INSERT INTO ProductName VALUES ('Reynard');
INSERT INTO ProductName VALUES ('Pennywise');
INSERT INTO ProductName VALUES ('Intricate Ivory');
INSERT INTO ProductName VALUES ('Sweet Orange');
INSERT INTO ProductName VALUES ('Soft Apricot');
INSERT INTO ProductName VALUES ('Chivalry Copper');
INSERT INTO ProductName VALUES ('Armagnac');
INSERT INTO ProductName VALUES ('Truepenny');
INSERT INTO ProductName VALUES ('Copper Mountain');
INSERT INTO ProductName VALUES ('Choice Cream');
INSERT INTO ProductName VALUES ('Creamery');
INSERT INTO ProductName VALUES ('Sociable');
INSERT INTO ProductName VALUES ('Folksy Gold');
INSERT INTO ProductName VALUES ('Autumnal');
INSERT INTO ProductName VALUES ('Tigereye');
INSERT INTO ProductName VALUES ('Gingery');
INSERT INTO ProductName VALUES ('Eggwhite');
INSERT INTO ProductName VALUES ('Cachet Cream');
INSERT INTO ProductName VALUES ('Ambitious Amber');
INSERT INTO ProductName VALUES ('Viva Gold');
INSERT INTO ProductName VALUES ('Bakelite Gold');
INSERT INTO ProductName VALUES ('T assel');
INSERT INTO ProductName VALUES ('Saucy Gold');
INSERT INTO ProductName VALUES ('Vanillin');
INSERT INTO ProductName VALUES ('Inviting Ivory');
INSERT INTO ProductName VALUES ('Harvester');
INSERT INTO ProductName VALUES ('T orchlight');
INSERT INTO ProductName VALUES ('Honeycomb');
INSERT INTO ProductName VALUES ('Gold Coast');
INSERT INTO ProductName VALUES ('Butterscotch');
INSERT INTO ProductName VALUES ('Crisp Linen');
INSERT INTO ProductName VALUES ('Jersey Cream');
INSERT INTO ProductName VALUES ('Humble Gold');
INSERT INTO ProductName VALUES ('Anjou Pear');
INSERT INTO ProductName VALUES ('Ceremonial Gold');
INSERT INTO ProductName VALUES ('Golden Rule');
INSERT INTO ProductName VALUES ('Cut The Mustard');
INSERT INTO ProductName VALUES ('Dover White');
INSERT INTO ProductName VALUES ('Napery');
INSERT INTO ProductName VALUES ('Compatible Cream');
INSERT INTO ProductName VALUES ('Golden Fleece');
INSERT INTO ProductName VALUES ('Butternut');
INSERT INTO ProductName VALUES ('Bosc Pear');
INSERT INTO ProductName VALUES ('Gallant Gold');
INSERT INTO ProductName VALUES ('Vital Yellow');
INSERT INTO ProductName VALUES ('Convivial Yellow');
INSERT INTO ProductName VALUES ('Sequin');
INSERT INTO ProductName VALUES ('Alchemy');
INSERT INTO ProductName VALUES ('Different Gold');
INSERT INTO ProductName VALUES ('Nankeen');
INSERT INTO ProductName VALUES ('Sconce Gold');
INSERT INTO ProductName VALUES ('Chamomile');
INSERT INTO ProductName VALUES ('Lucent Yellow');
INSERT INTO ProductName VALUES ('Independent Gold');
INSERT INTO ProductName VALUES ('Antiquity');
INSERT INTO ProductName VALUES ('Escapade Gold');
INSERT INTO ProductName VALUES ('Grandiose');
INSERT INTO ProductName VALUES ('Fervent Brass');
INSERT INTO ProductName VALUES ('Ionic Ivory');
INSERT INTO ProductName VALUES ('Ancestral Gold');
INSERT INTO ProductName VALUES ('Wheat Grass');
INSERT INTO ProductName VALUES ('Edgy Gold');
INSERT INTO ProductName VALUES ('Brassy');
INSERT INTO ProductName VALUES ('Bengal Grass');
INSERT INTO ProductName VALUES ('Eminent Bronze');
INSERT INTO ProductName VALUES ('Restoration Ivory');
INSERT INTO ProductName VALUES ('Rice Paddy');
INSERT INTO ProductName VALUES ('Hearts Of Palm');
INSERT INTO ProductName VALUES ('Sassy Green');
INSERT INTO ProductName VALUES ('Tupelo Tree');
INSERT INTO ProductName VALUES ('Rural Green');
INSERT INTO ProductName VALUES ('Saguaro');
INSERT INTO ProductName VALUES ('Queen Anne''s Lace');
INSERT INTO ProductName VALUES ('Celery');
INSERT INTO ProductName VALUES ('Shagreen');
INSERT INTO ProductName VALUES ('Ryegrass');
INSERT INTO ProductName VALUES ('Tansy Green');
INSERT INTO ProductName VALUES ('Relentless Olive');
INSERT INTO ProductName VALUES ('Basque Green');
INSERT INTO ProductName VALUES ('Sprout');
INSERT INTO ProductName VALUES ('Honeydew');
INSERT INTO ProductName VALUES ('Baize Green');
INSERT INTO ProductName VALUES ('Great Green');
INSERT INTO ProductName VALUES ('Leapfrog');
INSERT INTO ProductName VALUES ('Garden Spot');
INSERT INTO ProductName VALUES ('Inverness');
INSERT INTO ProductName VALUES ('Spinach White');
INSERT INTO ProductName VALUES ('Gratifying Green');
INSERT INTO ProductName VALUES ('Bonsai Tint');
INSERT INTO ProductName VALUES ('Haven');
INSERT INTO ProductName VALUES ('Dill');
INSERT INTO ProductName VALUES ('Greenfield');
INSERT INTO ProductName VALUES ('Courtyard');
INSERT INTO ProductName VALUES ('White Mint');
INSERT INTO ProductName VALUES ('Supreme Green');
INSERT INTO ProductName VALUES ('Relish');
INSERT INTO ProductName VALUES ('Lounge Green');
INSERT INTO ProductName VALUES ('Garden Grove');
INSERT INTO ProductName VALUES ('Arugula');
INSERT INTO ProductName VALUES ('Evergreens');
INSERT INTO ProductName VALUES ('Greening');
INSERT INTO ProductName VALUES ('Topiary Tint');
INSERT INTO ProductName VALUES ('Easy Green');
INSERT INTO ProductName VALUES ('Nurture Green');
INSERT INTO ProductName VALUES ('Inland');
INSERT INTO ProductName VALUES ('Cilantro');
INSERT INTO ProductName VALUES ('Shamrock');
INSERT INTO ProductName VALUES ('Fleeting Green');
INSERT INTO ProductName VALUES ('Slow Green');
INSERT INTO ProductName VALUES ('Kind Green');
INSERT INTO ProductName VALUES ('Restful');
INSERT INTO ProductName VALUES ('Jadite');
INSERT INTO ProductName VALUES ('Kale Green');
INSERT INTO ProductName VALUES ('Isle Of Pines');
INSERT INTO ProductName VALUES ('Green Trance');
INSERT INTO ProductName VALUES ('Breaktime');
INSERT INTO ProductName VALUES ('Aloe');
INSERT INTO ProductName VALUES ('Spearmint');
INSERT INTO ProductName VALUES ('Grandview');
INSERT INTO ProductName VALUES ('Kendal Green');
INSERT INTO ProductName VALUES ('Hunt Club');
INSERT INTO ProductName VALUES ('Dewy');
INSERT INTO ProductName VALUES ('W aterscape');
INSERT INTO ProductName VALUES ('Hazel');
INSERT INTO ProductName VALUES ('Composed');
INSERT INTO ProductName VALUES ('Surf Green');
INSERT INTO ProductName VALUES ('Raging Sea');
INSERT INTO ProductName VALUES ('Country Squire');
INSERT INTO ProductName VALUES ('Glimmer');
INSERT INTO ProductName VALUES ('Tidewater');
INSERT INTO ProductName VALUES ('W atery');
INSERT INTO ProductName VALUES ('Drizzle');
INSERT INTO ProductName VALUES ('Lagoon');
INSERT INTO ProductName VALUES ('Green Bay');
INSERT INTO ProductName VALUES ('Cape Verde');
INSERT INTO ProductName VALUES ('Buoyant Blue');
INSERT INTO ProductName VALUES ('Meander Blue');
INSERT INTO ProductName VALUES ('Raindrop');
INSERT INTO ProductName VALUES ('Reflecting Pool');
INSERT INTO ProductName VALUES ('Cloudburst');
INSERT INTO ProductName VALUES ('Grand Canal');
INSERT INTO ProductName VALUES ('Really Teal');
INSERT INTO ProductName VALUES ('Timid Blue');
INSERT INTO ProductName VALUES ('Open Air');
INSERT INTO ProductName VALUES ('Jetstream');
INSERT INTO ProductName VALUES ('Ebbtide');
INSERT INTO ProductName VALUES ('Lakeshore');
INSERT INTO ProductName VALUES ('Great Falls');
INSERT INTO ProductName VALUES ('Oceanside');
INSERT INTO ProductName VALUES ('Blue Horizon');
INSERT INTO ProductName VALUES ('Byte Blue');
INSERT INTO ProductName VALUES ('Stream');
INSERT INTO ProductName VALUES ('Open Seas');
INSERT INTO ProductName VALUES ('Manitou Blue');
INSERT INTO ProductName VALUES ('Loch Blue');
INSERT INTO ProductName VALUES ('Bosporus');
INSERT INTO ProductName VALUES ('Sky High');
INSERT INTO ProductName VALUES ('Atmospheric');
INSERT INTO ProductName VALUES ('Vast Sky');
INSERT INTO ProductName VALUES ('Resolute Blue');
INSERT INTO ProductName VALUES ('Secure Blue');
INSERT INTO ProductName VALUES ('Georgian Bay');
INSERT INTO ProductName VALUES ('Loyal Blue');
INSERT INTO ProductName VALUES ('Snowdrop');
INSERT INTO ProductName VALUES ('Balmy');
INSERT INTO ProductName VALUES ('Take Five');
INSERT INTO ProductName VALUES ('Respite');
INSERT INTO ProductName VALUES ('Leisure Blue');
INSERT INTO ProductName VALUES ('Down Pour');
INSERT INTO ProductName VALUES ('Regatta');
INSERT INTO ProductName VALUES ('Ski Slope');
INSERT INTO ProductName VALUES ('Hinting Blue');
INSERT INTO ProductName VALUES ('Honest Blue');
INSERT INTO ProductName VALUES ('Notable Hue');
INSERT INTO ProductName VALUES ('Sporty Blue');
INSERT INTO ProductName VALUES ('Denim');
INSERT INTO ProductName VALUES ('Commodore');
INSERT INTO ProductName VALUES ('Rarified Air');
INSERT INTO ProductName VALUES ('Icelandic');
INSERT INTO ProductName VALUES ('Blissful Blue');
INSERT INTO ProductName VALUES ('Cosmos');
INSERT INTO ProductName VALUES ('Scanda');
INSERT INTO ProductName VALUES ('Revel Blue');
INSERT INTO ProductName VALUES ('Indigo');
INSERT INTO ProductName VALUES ('Aura White');
INSERT INTO ProductName VALUES ('Mild Blue');
INSERT INTO ProductName VALUES ('Icy');
INSERT INTO ProductName VALUES ('Solitude');
INSERT INTO ProductName VALUES ('Searching Blue');
INSERT INTO ProductName VALUES ('Luxe Blue');
INSERT INTO ProductName VALUES ('Dignified');
INSERT INTO ProductName VALUES ('Soothing White');
INSERT INTO ProductName VALUES ('Starry Night');
INSERT INTO ProductName VALUES ('Daydream');
INSERT INTO ProductName VALUES ('Vesper Violet');
INSERT INTO ProductName VALUES ('Soulful Blue');
INSERT INTO ProductName VALUES ('Mesmerize');
INSERT INTO ProductName VALUES ('Majestic Purple');
INSERT INTO ProductName VALUES ('Cloud Nine');
INSERT INTO ProductName VALUES ('Silver Peony');
INSERT INTO ProductName VALUES ('Grape Mist');
INSERT INTO ProductName VALUES ('Ash Violet');
INSERT INTO ProductName VALUES ('Mythical');
INSERT INTO ProductName VALUES ('Purple Passage');
INSERT INTO ProductName VALUES ('Dewberry');
INSERT INTO ProductName VALUES ('Heavenly White');
INSERT INTO ProductName VALUES ('Lite Lavender');
INSERT INTO ProductName VALUES ('Enchant');
INSERT INTO ProductName VALUES ('Obi Lilac');
INSERT INTO ProductName VALUES ('Wood Violet');
INSERT INTO ProductName VALUES ('Plummy');
INSERT INTO ProductName VALUES ('Concord Grape');
INSERT INTO ProductName VALUES ('Venus Pink');
INSERT INTO ProductName VALUES ('T eaberry');
INSERT INTO ProductName VALUES ('Irresistible');
INSERT INTO ProductName VALUES ('Rosebay');
INSERT INTO ProductName VALUES ('Red Clover');
INSERT INTO ProductName VALUES ('Grandeur Plum');
INSERT INTO ProductName VALUES ('Framboise');
INSERT INTO ProductName VALUES ('Anemone');
INSERT INTO ProductName VALUES ('Lighthearted Pink');
INSERT INTO ProductName VALUES ('Childlike');
INSERT INTO ProductName VALUES ('Haute Pink');
INSERT INTO ProductName VALUES ('Cyclamen');
INSERT INTO ProductName VALUES ('Ruby Shade');
INSERT INTO ProductName VALUES ('Juneberry');
INSERT INTO ProductName VALUES ('Rosily');
INSERT INTO ProductName VALUES ('Priscilla');
INSERT INTO ProductName VALUES ('Azalea Flower');
INSERT INTO ProductName VALUES ('Jaipur Pink');
INSERT INTO ProductName VALUES ('Tuberose');
INSERT INTO ProductName VALUES ('Gala Pink');
INSERT INTO ProductName VALUES ('Cerise');
INSERT INTO ProductName VALUES ('Verbena');
INSERT INTO ProductName VALUES ('Impatiens Petal');
INSERT INTO ProductName VALUES ('In The Pink');
INSERT INTO ProductName VALUES ('Cheery');
INSERT INTO ProductName VALUES ('Coming Up Roses');
INSERT INTO ProductName VALUES ('Heartfelt');
INSERT INTO ProductName VALUES ('Valentine');
INSERT INTO ProductName VALUES ('Diminutive Pink');
INSERT INTO ProductName VALUES ('Alyssum');
INSERT INTO ProductName VALUES ('Loveable');
INSERT INTO ProductName VALUES ('Amaryllis');
INSERT INTO ProductName VALUES ('Grenadine');
INSERT INTO ProductName VALUES ('Coral Bells');
INSERT INTO ProductName VALUES ('Poinsettia');
INSERT INTO ProductName VALUES ('Amour Pink');
INSERT INTO ProductName VALUES ('Bella Pink');
INSERT INTO ProductName VALUES ('Hopeful');
INSERT INTO ProductName VALUES ('Dishy Coral');
INSERT INTO ProductName VALUES ('Begonia');
INSERT INTO ProductName VALUES ('Enticing Red');
INSERT INTO ProductName VALUES ('T anager');
INSERT INTO ProductName VALUES ('Angelic');
INSERT INTO ProductName VALUES ('Oleander');
INSERT INTO ProductName VALUES ('Youthful Coral');
INSERT INTO ProductName VALUES ('Charisma');
INSERT INTO ProductName VALUES ('Coral Reef');
INSERT INTO ProductName VALUES ('Red Tomato');
INSERT INTO ProductName VALUES ('Rave Red');
INSERT INTO ProductName VALUES ('Touching White');
INSERT INTO ProductName VALUES ('Koral Kicks');
INSERT INTO ProductName VALUES ('Jovial');
INSERT INTO ProductName VALUES ('Ravishing Coral');
INSERT INTO ProductName VALUES ('Lei Flower');
INSERT INTO ProductName VALUES ('Quite Coral');
INSERT INTO ProductName VALUES ('Peppery');
INSERT INTO ProductName VALUES ('Feather White');
INSERT INTO ProductName VALUES ('Blushing');
INSERT INTO ProductName VALUES ('Cosmetic Peach');
INSERT INTO ProductName VALUES ('Sockeye');
INSERT INTO ProductName VALUES ('Rejuvenate');
INSERT INTO ProductName VALUES ('Emotional');
INSERT INTO ProductName VALUES ('Hearty Orange');
INSERT INTO ProductName VALUES ('Teasing Peach');
INSERT INTO ProductName VALUES ('Peach Blossom');
INSERT INTO ProductName VALUES ('Certain Peach');
INSERT INTO ProductName VALUES ('Sunset');
INSERT INTO ProductName VALUES ('Emberglow');
INSERT INTO ProductName VALUES ('Robust Orange');
INSERT INTO ProductName VALUES ('Jalape£¿o');
INSERT INTO ProductName VALUES ('Posy');
INSERT INTO ProductName VALUES ('Naive Peach');
INSERT INTO ProductName VALUES ('Neighborly Peach');
INSERT INTO ProductName VALUES ('Inventive Orange');
INSERT INTO ProductName VALUES ('Copper Harbor');
INSERT INTO ProductName VALUES ('Determined Orange');
INSERT INTO ProductName VALUES ('Husky Orange');
INSERT INTO ProductName VALUES ('Organza');
INSERT INTO ProductName VALUES ('Flattering Peach');
INSERT INTO ProductName VALUES ('Avid Apricot');
INSERT INTO ProductName VALUES ('T angerine');
INSERT INTO ProductName VALUES ('Outgoing Orange');
INSERT INTO ProductName VALUES ('Rhumba Orange');
INSERT INTO ProductName VALUES ('Yam');
INSERT INTO ProductName VALUES ('Champagne');
INSERT INTO ProductName VALUES ('Frangipane');
INSERT INTO ProductName VALUES ('Orange Blast');
INSERT INTO ProductName VALUES ('Exciting Orange');
INSERT INTO ProductName VALUES ('Kumquat');
INSERT INTO ProductName VALUES ('T ango');
INSERT INTO ProductName VALUES ('Marquis Orange');
INSERT INTO ProductName VALUES ('Cherish Cream');
INSERT INTO ProductName VALUES ('Flan');
INSERT INTO ProductName VALUES ('Delicious Melon');
INSERT INTO ProductName VALUES ('Surprise Amber');
INSERT INTO ProductName VALUES ('Adventure Orange');
INSERT INTO ProductName VALUES ('Serape');
INSERT INTO ProductName VALUES ('Amber Wave');
INSERT INTO ProductName VALUES ('Welcome White');
INSERT INTO ProductName VALUES ('Captivating Cream');
INSERT INTO ProductName VALUES ('Honey Blush');
INSERT INTO ProductName VALUES ('Papaya');
INSERT INTO ProductName VALUES ('Summer Day');
INSERT INTO ProductName VALUES ('Saffron Thread');
INSERT INTO ProductName VALUES ('Marigold');
INSERT INTO ProductName VALUES ('Gardenia');
INSERT INTO ProductName VALUES ('Enjoyable Yellow');
INSERT INTO ProductName VALUES ('Afterglow');
INSERT INTO ProductName VALUES ('Sunrise');
INSERT INTO ProductName VALUES ('Yarrow');
INSERT INTO ProductName VALUES ('Gold Crest');
INSERT INTO ProductName VALUES ('Curry');
INSERT INTO ProductName VALUES ('Morning Sun');
INSERT INTO ProductName VALUES ('Banana Cream');
INSERT INTO ProductName VALUES ('Jonquil');
INSERT INTO ProductName VALUES ('Afternoon');
INSERT INTO ProductName VALUES ('Butterfield');
INSERT INTO ProductName VALUES ('Goldenrod');
INSERT INTO ProductName VALUES ('Sunflower');
INSERT INTO ProductName VALUES ('Full Moon');
INSERT INTO ProductName VALUES ('Friendly Yellow');
INSERT INTO ProductName VALUES ('Butter Up');
INSERT INTO ProductName VALUES ('June Day');
INSERT INTO ProductName VALUES ('Bee');
INSERT INTO ProductName VALUES ('Brittlebush');
INSERT INTO ProductName VALUES ('Trinket');
INSERT INTO ProductName VALUES ('Lemon Chiffon');
INSERT INTO ProductName VALUES ('Lantern Light');
INSERT INTO ProductName VALUES ('Solaria');
INSERT INTO ProductName VALUES ('Overjoy');
INSERT INTO ProductName VALUES ('Gambol Gold');
INSERT INTO ProductName VALUES ('Glitzy Gold');
INSERT INTO ProductName VALUES ('Auric');
INSERT INTO ProductName VALUES ('Lily');
INSERT INTO ProductName VALUES ('Glad Yellow');
INSERT INTO ProductName VALUES ('Midday');
INSERT INTO ProductName VALUES ('Quilt Gold');
INSERT INTO ProductName VALUES ('Nugget');
INSERT INTO ProductName VALUES ('Kingdom Gold');
INSERT INTO ProductName VALUES ('Crispy Gold');
INSERT INTO ProductName VALUES ('Daybreak');
INSERT INTO ProductName VALUES ('Moonraker');
INSERT INTO ProductName VALUES ('Lively Yellow');
INSERT INTO ProductName VALUES ('Frolic');
INSERT INTO ProductName VALUES ('Hep Green');
INSERT INTO ProductName VALUES ('High Strung');
INSERT INTO ProductName VALUES ('Offbeat Green');
INSERT INTO ProductName VALUES ('Narcissus');
INSERT INTO ProductName VALUES ('Springtime');
INSERT INTO ProductName VALUES ('Gleeful');
INSERT INTO ProductName VALUES ('M ̈¦lange Green');
INSERT INTO ProductName VALUES ('Parakeet');
INSERT INTO ProductName VALUES ('Luau Green');
INSERT INTO ProductName VALUES ('Verdant');
INSERT INTO ProductName VALUES ('Citrine');
INSERT INTO ProductName VALUES ('Lime Granita');
INSERT INTO ProductName VALUES ('Dancing Green');
INSERT INTO ProductName VALUES ('Lime Rickey');
INSERT INTO ProductName VALUES ('Overt Green');
INSERT INTO ProductName VALUES ('Gecko');
INSERT INTO ProductName VALUES ('Paradise');
INSERT INTO ProductName VALUES ('Enlightened Lime');
INSERT INTO ProductName VALUES ('Cucumber');
INSERT INTO ProductName VALUES ('Jardin');
INSERT INTO ProductName VALUES ('Mesclun Green');
INSERT INTO ProductName VALUES ('Pickle');
INSERT INTO ProductName VALUES ('Talipot Palm');
INSERT INTO ProductName VALUES ('Houseplant');
INSERT INTO ProductName VALUES ('White Willow');
INSERT INTO ProductName VALUES ('Lacewing');
INSERT INTO ProductName VALUES ('Romaine');
INSERT INTO ProductName VALUES ('Picnic');
INSERT INTO ProductName VALUES ('Organic Green');
INSERT INTO ProductName VALUES ('Grasshopper');
INSERT INTO ProductName VALUES ('Espalier');
INSERT INTO ProductName VALUES ('Minted');
INSERT INTO ProductName VALUES ('Jocular Green');
INSERT INTO ProductName VALUES ('Kiwi');
INSERT INTO ProductName VALUES ('Vegan');
INSERT INTO ProductName VALUES ('Eco Green');
INSERT INTO ProductName VALUES ('Kilkenny');
INSERT INTO ProductName VALUES ('Derbyshire');
INSERT INTO ProductName VALUES ('Lighter Mint');
INSERT INTO ProductName VALUES ('Mint Condition');
INSERT INTO ProductName VALUES ('Reclining Green');
INSERT INTO ProductName VALUES ('Lark Green');
INSERT INTO ProductName VALUES ('Julep');
INSERT INTO ProductName VALUES ('Argyle');
INSERT INTO ProductName VALUES ('Greens');
INSERT INTO ProductName VALUES ('Embellished Blue');
INSERT INTO ProductName VALUES ('W aterfall');
INSERT INTO ProductName VALUES ('Refresh');
INSERT INTO ProductName VALUES ('Larchmere');
INSERT INTO ProductName VALUES ('Jargon Jade');
INSERT INTO ProductName VALUES ('Ionian');
INSERT INTO ProductName VALUES ('Starboard');
INSERT INTO ProductName VALUES ('Crystal Clear');
INSERT INTO ProductName VALUES ('Tame Teal');
INSERT INTO ProductName VALUES ('Aqueduct');
INSERT INTO ProductName VALUES ('Cooled Blue');
INSERT INTO ProductName VALUES ('Rivulet');
INSERT INTO ProductName VALUES ('Thermal Spring');
INSERT INTO ProductName VALUES ('Poseidon');
INSERT INTO ProductName VALUES ('Retiring Blue');
INSERT INTO ProductName VALUES ('Swimming');
INSERT INTO ProductName VALUES ('Spa');
INSERT INTO ProductName VALUES ('Mariner');
INSERT INTO ProductName VALUES ('Aquarium');
INSERT INTO ProductName VALUES ('Gulfstream');
INSERT INTO ProductName VALUES ('Maxi Teal');
INSERT INTO ProductName VALUES ('Bubble');
INSERT INTO ProductName VALUES ('Bathe Blue');
INSERT INTO ProductName VALUES ('Cay');
INSERT INTO ProductName VALUES ('Rapture Blue');
INSERT INTO ProductName VALUES ('Freshwater');
INSERT INTO ProductName VALUES ('Briny');
INSERT INTO ProductName VALUES ('Blue Nile');
INSERT INTO ProductName VALUES ('Carefree');
INSERT INTO ProductName VALUES ('Aviary Blue');
INSERT INTO ProductName VALUES ('Liquid Blue');
INSERT INTO ProductName VALUES ('Nautilus');
INSERT INTO ProductName VALUES ('Jamaica Bay');
INSERT INTO ProductName VALUES ('Cruising');
INSERT INTO ProductName VALUES ('Amalfi');
INSERT INTO ProductName VALUES ('Bravo Blue');
INSERT INTO ProductName VALUES ('Quench Blue');
INSERT INTO ProductName VALUES ('Cloudless');
INSERT INTO ProductName VALUES ('Fountain');
INSERT INTO ProductName VALUES ('Capri');
INSERT INTO ProductName VALUES ('Blue Mosque');
INSERT INTO ProductName VALUES ('Adriatic Sea');
INSERT INTO ProductName VALUES ('Lauren''s Surprise');
INSERT INTO ProductName VALUES ('Minor Blue');
INSERT INTO ProductName VALUES ('Bluebell');
INSERT INTO ProductName VALUES ('Flyway');
INSERT INTO ProductName VALUES ('Major Blue');
INSERT INTO ProductName VALUES ('Blue Plate');
INSERT INTO ProductName VALUES ('Jay Blue');
INSERT INTO ProductName VALUES ('Iceberg');
INSERT INTO ProductName VALUES ('Soar');
INSERT INTO ProductName VALUES ('Something Blue');
INSERT INTO ProductName VALUES ('Regale Blue');
INSERT INTO ProductName VALUES ('Jacaranda');
INSERT INTO ProductName VALUES ('Danube');
INSERT INTO ProductName VALUES ('Dignity Blue');
INSERT INTO ProductName VALUES ('Glass Bead');
INSERT INTO ProductName VALUES ('Rhythmic Blue');
INSERT INTO ProductName VALUES ('Wondrous Blue');
INSERT INTO ProductName VALUES ('Celestial');
INSERT INTO ProductName VALUES ('Lobelia');
INSERT INTO ProductName VALUES ('Lupine');
INSERT INTO ProductName VALUES ('Honorable Blue');
INSERT INTO ProductName VALUES ('White Iris');
INSERT INTO ProductName VALUES ('Wishful Blue');
INSERT INTO ProductName VALUES ('Breathtaking');
INSERT INTO ProductName VALUES ('Awesome Violet');
INSERT INTO ProductName VALUES ('Dahlia');
INSERT INTO ProductName VALUES ('Gentian');
INSERT INTO ProductName VALUES ('Valiant Violet');
INSERT INTO ProductName VALUES ('Minuet White');
INSERT INTO ProductName VALUES ('Inspired Lilac');
INSERT INTO ProductName VALUES ('Potentially Purple');
INSERT INTO ProductName VALUES ('Wisteria');
INSERT INTO ProductName VALUES ('Brave Purple');
INSERT INTO ProductName VALUES ('Forget-Me-Not');
INSERT INTO ProductName VALUES ('Izmir Purple');
INSERT INTO ProductName VALUES ('Whimsical White');
INSERT INTO ProductName VALUES ('Elation');
INSERT INTO ProductName VALUES ('Rhapsody Lilac');
INSERT INTO ProductName VALUES ('Magical');
INSERT INTO ProductName VALUES ('Kismet');
INSERT INTO ProductName VALUES ('Clematis');
INSERT INTO ProductName VALUES ('Impulsive Purple');
INSERT INTO ProductName VALUES ('White Lilac');
INSERT INTO ProductName VALUES ('Spangle');
INSERT INTO ProductName VALUES ('Euphoric Lilac');
INSERT INTO ProductName VALUES ('Novel Lilac');
INSERT INTO ProductName VALUES ('Baroness');
INSERT INTO ProductName VALUES ('Vigorous Violet');
INSERT INTO ProductName VALUES ('Kimono Violet');
INSERT INTO ProductName VALUES ('Exuberant Pink');
INSERT INTO ProductName VALUES ('Dynamo');
INSERT INTO ProductName VALUES ('Forward Fuschia');
INSERT INTO ProductName VALUES ('Hot');
INSERT INTO ProductName VALUES ('Merry Pink');
INSERT INTO ProductName VALUES ('Child''s Play');
INSERT INTO ProductName VALUES ('Prominent Pink');
INSERT INTO ProductName VALUES ('Ice Plant');
INSERT INTO ProductName VALUES ('Panache Pink');
INSERT INTO ProductName VALUES ('Partytime');
INSERT INTO ProductName VALUES ('Vivacious Pink');
INSERT INTO ProductName VALUES ('Hibiscus');
INSERT INTO ProductName VALUES ('Desire Pink');
INSERT INTO ProductName VALUES ('Fussy Pink');
INSERT INTO ProductName VALUES ('Impatient Pink');
INSERT INTO ProductName VALUES ('Dragon Fruit');
INSERT INTO ProductName VALUES ('Reverie Pink');
INSERT INTO ProductName VALUES ('Pink Moment');
INSERT INTO ProductName VALUES ('Zany Pink');
INSERT INTO ProductName VALUES ('Feverish Pink');
INSERT INTO ProductName VALUES ('Eros Pink');
INSERT INTO ProductName VALUES ('Radish');
INSERT INTO ProductName VALUES ('Cherries Jubilee');
INSERT INTO ProductName VALUES ('Lusty Red');
INSERT INTO ProductName VALUES ('Cherry Tomato');
INSERT INTO ProductName VALUES ('Gypsy Red');
INSERT INTO ProductName VALUES ('Heartthrob');
INSERT INTO ProductName VALUES ('Fireworks');
INSERT INTO ProductName VALUES ('Real Red');
INSERT INTO ProductName VALUES ('Stop');
INSERT INTO ProductName VALUES ('Ablaze');
INSERT INTO ProductName VALUES ('Positive Red');
INSERT INTO ProductName VALUES ('Gaiety');
INSERT INTO ProductName VALUES ('Coral Bead');
INSERT INTO ProductName VALUES ('Ardent Coral');
INSERT INTO ProductName VALUES ('Gladiola');
INSERT INTO ProductName VALUES ('Comical Coral');
INSERT INTO ProductName VALUES ('Inner Child');
INSERT INTO ProductName VALUES ('Animated Coral');
INSERT INTO ProductName VALUES ('Daring');
INSERT INTO ProductName VALUES ('Energetic Orange');
INSERT INTO ProductName VALUES ('Cayenne');
INSERT INTO ProductName VALUES ('Daredevil');
INSERT INTO ProductName VALUES ('Raucous Orange');
INSERT INTO ProductName VALUES ('Obstinate Orange');
INSERT INTO ProductName VALUES ('Knockout Orange');
INSERT INTO ProductName VALUES ('Invigorate');
INSERT INTO ProductName VALUES ('Navel');
INSERT INTO ProductName VALUES ('Pizazz Peach');
INSERT INTO ProductName VALUES ('Stirring Orange');
INSERT INTO ProductName VALUES ('Osage Orange');
INSERT INTO ProductName VALUES ('Mandarin');
INSERT INTO ProductName VALUES ('Carnival');
INSERT INTO ProductName VALUES ('Kid''s Stuff');
INSERT INTO ProductName VALUES ('Forceful Orange');
INSERT INTO ProductName VALUES ('Laughing Orange');
INSERT INTO ProductName VALUES ('Sol ̈¦');
INSERT INTO ProductName VALUES ('Sundance');
INSERT INTO ProductName VALUES ('Social Butterfly');
INSERT INTO ProductName VALUES ('Nasturtium');
INSERT INTO ProductName VALUES ('Optimistic Yellow');
INSERT INTO ProductName VALUES ('Daffodil');
INSERT INTO ProductName VALUES ('Decisive Yellow');
INSERT INTO ProductName VALUES ('Cheerful');
INSERT INTO ProductName VALUES ('Gusto Gold');
INSERT INTO ProductName VALUES ('Goldfinch');
INSERT INTO ProductName VALUES ('Citrus');
INSERT INTO ProductName VALUES ('Forsythia');
INSERT INTO ProductName VALUES ('Fun Yellow');
INSERT INTO ProductName VALUES ('Lemon Twist');
INSERT INTO ProductName VALUES ('Daisy');
INSERT INTO ProductName VALUES ('Confident Yellow');
INSERT INTO ProductName VALUES ('Glisten Yellow');
INSERT INTO ProductName VALUES ('Funky Yellow');
INSERT INTO ProductName VALUES ('Eye Catching');
INSERT INTO ProductName VALUES ('Citronella');
INSERT INTO ProductName VALUES ('Impetuous');
INSERT INTO ProductName VALUES ('Nervy Hue');
INSERT INTO ProductName VALUES ('Humorous Green');
INSERT INTO ProductName VALUES ('Fusion');
INSERT INTO ProductName VALUES ('Center Stage');
INSERT INTO ProductName VALUES ('Electric Lime');
INSERT INTO ProductName VALUES ('Outrageous Green');
INSERT INTO ProductName VALUES ('Festival Green');
INSERT INTO ProductName VALUES ('Direct Green');
INSERT INTO ProductName VALUES ('Envy');
INSERT INTO ProductName VALUES ('Lucky Green');
INSERT INTO ProductName VALUES ('Greenbelt');
INSERT INTO ProductName VALUES ('Green Vibes');
INSERT INTO ProductName VALUES ('Witty Green');
INSERT INTO ProductName VALUES ('Laudable Lime');
INSERT INTO ProductName VALUES ('Jolly Green');
INSERT INTO ProductName VALUES ('Spirited Green');
INSERT INTO ProductName VALUES ('Clean Green');
INSERT INTO ProductName VALUES ('Rally Green');
INSERT INTO ProductName VALUES ('Straightforward Green');
INSERT INTO ProductName VALUES ('Aquatint');
INSERT INTO ProductName VALUES ('Tantalizing Teal');
INSERT INTO ProductName VALUES ('Synergy');
INSERT INTO ProductName VALUES ('Turquish');
INSERT INTO ProductName VALUES ('Biscay');
INSERT INTO ProductName VALUES ('Nifty Turquoise');
INSERT INTO ProductName VALUES ('Splashy');
INSERT INTO ProductName VALUES ('Intense Teal');
INSERT INTO ProductName VALUES ('Pool Blue');
INSERT INTO ProductName VALUES ('Belize');
INSERT INTO ProductName VALUES ('Surfer');
INSERT INTO ProductName VALUES ('Tempo Teal');
INSERT INTO ProductName VALUES ('Blue Bauble');
INSERT INTO ProductName VALUES ('Slick Blue');
INSERT INTO ProductName VALUES ('Calypso');
INSERT INTO ProductName VALUES ('Cote D''Azur');
INSERT INTO ProductName VALUES ('Blue Click');
INSERT INTO ProductName VALUES ('Candid Blue');
INSERT INTO ProductName VALUES ('Resonant Blue');
INSERT INTO ProductName VALUES ('Impromptu');
INSERT INTO ProductName VALUES ('Blue Refrain');
INSERT INTO ProductName VALUES ('Undercool');
INSERT INTO ProductName VALUES ('Dynamic Blue');
INSERT INTO ProductName VALUES ('Blue Chip');
INSERT INTO ProductName VALUES ('Bewitching Blue');
INSERT INTO ProductName VALUES ('Blue Beyond');
INSERT INTO ProductName VALUES ('Dazzle');
INSERT INTO ProductName VALUES ('Sapphire');
INSERT INTO ProductName VALUES ('Pulsating Blue');
INSERT INTO ProductName VALUES ('Hyper Blue');
INSERT INTO ProductName VALUES ('Blueblood');
INSERT INTO ProductName VALUES ('Frank Blue');
INSERT INTO ProductName VALUES ('Hyacinth Tint');
INSERT INTO ProductName VALUES ('Indulgent');
INSERT INTO ProductName VALUES ('Venture Violet');
INSERT INTO ProductName VALUES ('Morning Glory');
INSERT INTO ProductName VALUES ('Joyful Lilac');
INSERT INTO ProductName VALUES ('Free Spirit');
INSERT INTO ProductName VALUES ('Plum Blossom');
INSERT INTO ProductName VALUES ('Lavish Lavender');
INSERT INTO ProductName VALUES ('Vanity Pink');
INSERT INTO ProductName VALUES ('Queenly');
INSERT INTO ProductName VALUES ('Drama Violet');
INSERT INTO ProductName VALUES ('Verve Violet');
INSERT INTO ProductName VALUES ('Gutsy Grape');
INSERT INTO ProductName VALUES ('Passionate Purple');
INSERT INTO ProductName VALUES ('African Violet');
INSERT INTO ProductName VALUES ('Fully Purple');
INSERT INTO ProductName VALUES ('Bohemian Black');
INSERT INTO ProductName VALUES ('Domino');
INSERT INTO ProductName VALUES ('Caviar');
INSERT INTO ProductName VALUES ('Black Magic');
INSERT INTO ProductName VALUES ('Inkwell');
INSERT INTO ProductName VALUES ('Black Of Night');
INSERT INTO ProductName VALUES ('Greenblack');
INSERT INTO ProductName VALUES ('Superwhite');
INSERT INTO ProductName VALUES ('Ibis White');
INSERT INTO ProductName VALUES ('Marshmallow');
INSERT INTO ProductName VALUES ('Downy');
INSERT INTO ProductName VALUES ('Toque White');
INSERT INTO ProductName VALUES ('Snowbound');
INSERT INTO ProductName VALUES ('Pure White');
INSERT INTO ProductName VALUES ('Extra White');
INSERT INTO ProductName VALUES ('Ceiling Bright White');
INSERT INTO ProductName VALUES ('Alabaster');
INSERT INTO ProductName VALUES ('Pearly White');
INSERT INTO ProductName VALUES ('White Duck');
INSERT INTO ProductName VALUES ('Natural Choice');
INSERT INTO ProductName VALUES ('Creamy');
INSERT INTO ProductName VALUES ('Ivory Lace');
INSERT INTO ProductName VALUES ('Eider White');
INSERT INTO ProductName VALUES ('Repose Gray');
INSERT INTO ProductName VALUES ('Mindful Gray');
INSERT INTO ProductName VALUES ('Dorian Gray');
INSERT INTO ProductName VALUES ('Dovetail');
INSERT INTO ProductName VALUES ('Gauntlet Gray');
INSERT INTO ProductName VALUES ('Black Fox');
INSERT INTO ProductName VALUES ('Simple White');
INSERT INTO ProductName VALUES ('Alpaca');
INSERT INTO ProductName VALUES ('Requisite Gray');
INSERT INTO ProductName VALUES ('Functional Gray');
INSERT INTO ProductName VALUES ('Backdrop');
INSERT INTO ProductName VALUES ('Griffin');
INSERT INTO ProductName VALUES ('Well-Bred Brown');
INSERT INTO ProductName VALUES ('Incredible White');
INSERT INTO ProductName VALUES ('Agreeable Gray');
INSERT INTO ProductName VALUES ('Anew Gray');
INSERT INTO ProductName VALUES ('Mega Greige');
INSERT INTO ProductName VALUES ('Warm Stone');
INSERT INTO ProductName VALUES ('Brainstorm Bronze');
INSERT INTO ProductName VALUES ('Status Bronze');
INSERT INTO ProductName VALUES ('Aesthetic White');
INSERT INTO ProductName VALUES ('Accessible Beige');
INSERT INTO ProductName VALUES ('Balanced Beige');
INSERT INTO ProductName VALUES ('Tony Taupe');
INSERT INTO ProductName VALUES ('Virtual Taupe');
INSERT INTO ProductName VALUES ('Smokehouse');
INSERT INTO ProductName VALUES ('Van Dyke Brown');
INSERT INTO ProductName VALUES ('Shoji White');
INSERT INTO ProductName VALUES ('Worldly Gray');
INSERT INTO ProductName VALUES ('Amazing Gray');
INSERT INTO ProductName VALUES ('Intellectual Gray');
INSERT INTO ProductName VALUES ('Anonymous');
INSERT INTO ProductName VALUES ('Porpoise');
INSERT INTO ProductName VALUES ('Urbane Bronze');
INSERT INTO ProductName VALUES ('Nuance');
INSERT INTO ProductName VALUES ('Useful Gray');
INSERT INTO ProductName VALUES ('Analytical Gray');
INSERT INTO ProductName VALUES ('Gray Area');
INSERT INTO ProductName VALUES ('Adaptive Shade');
INSERT INTO ProductName VALUES ('Suitable Brown');
INSERT INTO ProductName VALUES ('Enduring Bronze');
INSERT INTO ProductName VALUES ('Reserved White');
INSERT INTO ProductName VALUES ('Silver Strand');
INSERT INTO ProductName VALUES ('Magnetic Gray');
INSERT INTO ProductName VALUES ('Unusual Gray');
INSERT INTO ProductName VALUES ('Attitude Gray');
INSERT INTO ProductName VALUES ('Night Owl');
INSERT INTO ProductName VALUES ('Rock Bottom');
INSERT INTO ProductName VALUES ('Nebulous White');
INSERT INTO ProductName VALUES ('Passive');
INSERT INTO ProductName VALUES ('Argos');
INSERT INTO ProductName VALUES ('Gray Matters');
INSERT INTO ProductName VALUES ('Cityscape');
INSERT INTO ProductName VALUES ('Grizzle Gray');
INSERT INTO ProductName VALUES ('Iron Ore');
INSERT INTO ProductName VALUES ('Site White');
INSERT INTO ProductName VALUES ('Gray Screen');
INSERT INTO ProductName VALUES ('Online');
INSERT INTO ProductName VALUES ('Network Gray');
INSERT INTO ProductName VALUES ('Software');
INSERT INTO ProductName VALUES ('Web Gray');
INSERT INTO ProductName VALUES ('Cyberspace');
INSERT INTO ProductName VALUES ('Original White');
INSERT INTO ProductName VALUES ('Minute Mauve');
INSERT INTO ProductName VALUES ('Ponder');
INSERT INTO ProductName VALUES ('Quest Gray');
INSERT INTO ProductName VALUES ('Sensuous Gray');
INSERT INTO ProductName VALUES ('Stunning Shade');
INSERT INTO ProductName VALUES ('Darkroom');
INSERT INTO ProductName VALUES ('Arcade White');
INSERT INTO ProductName VALUES ('Futon');
INSERT INTO ProductName VALUES ('White Flour');
INSERT INTO ProductName VALUES ('W hitetail');
INSERT INTO ProductName VALUES ('Cotton White');
INSERT INTO ProductName VALUES ('Paperwhite');
INSERT INTO ProductName VALUES ('Honied White');
INSERT INTO ProductName VALUES ('Fancy Pink');
INSERT INTO ProductName VALUES ('Pink Vibernum');
INSERT INTO ProductName VALUES ('Young At Heart');
INSERT INTO ProductName VALUES ('Cosmetic Blush');
INSERT INTO ProductName VALUES ('Laurel Pink');
INSERT INTO ProductName VALUES ('Pinkish');
INSERT INTO ProductName VALUES ('Roseate');
INSERT INTO ProductName VALUES ('Palish Peach');
INSERT INTO ProductName VALUES ('Conch Shell');
INSERT INTO ProductName VALUES ('A La Mode');
INSERT INTO ProductName VALUES ('Melon Tint');
INSERT INTO ProductName VALUES ('French Vanilla');
INSERT INTO ProductName VALUES ('Venetian Lace');
INSERT INTO ProductName VALUES ('Dollop Of Cream');
INSERT INTO ProductName VALUES ('Corona');
INSERT INTO ProductName VALUES ('Lemon Drop');
INSERT INTO ProductName VALUES ('Yellow Beam');
INSERT INTO ProductName VALUES ('Crescent Moon');
INSERT INTO ProductName VALUES ('Glittery Yellow');
INSERT INTO ProductName VALUES ('Pearl Onion');
INSERT INTO ProductName VALUES ('Apple Slice');
INSERT INTO ProductName VALUES ('Green Glaze');
INSERT INTO ProductName VALUES ('Opera Glass');
INSERT INTO ProductName VALUES ('Aquacade');
INSERT INTO ProductName VALUES ('Brooklet');
INSERT INTO ProductName VALUES ('Water Squirt');
INSERT INTO ProductName VALUES ('Faraway Blue');
INSERT INTO ProductName VALUES ('Tibetan Sky');
INSERT INTO ProductName VALUES ('Twinkle');
INSERT INTO ProductName VALUES ('Chapeau Violet');
INSERT INTO ProductName VALUES ('Violet Vignette');
INSERT INTO ProductName VALUES ('Lavender Wisp');
INSERT INTO ProductName VALUES ('Lady''s Slipper');
INSERT INTO ProductName VALUES ('Snowberry');
INSERT INTO ProductName VALUES ('Feathery Lilac');
INSERT INTO ProductName VALUES ('Threshold Taupe');
INSERT INTO ProductName VALUES ('Dry Dock');
INSERT INTO ProductName VALUES ('Sticks & Stones');
INSERT INTO ProductName VALUES ('Keystone Gray');
INSERT INTO ProductName VALUES ('Manor House');
INSERT INTO ProductName VALUES ('Loggia');
INSERT INTO ProductName VALUES ('Stone Lion');
INSERT INTO ProductName VALUES ('Tavern Taupe');
INSERT INTO ProductName VALUES ('Tiki Hut');
INSERT INTO ProductName VALUES ('Chateau Brown');
INSERT INTO ProductName VALUES ('Bungalow Beige');
INSERT INTO ProductName VALUES ('Pavillion Beige');
INSERT INTO ProductName VALUES ('Sanderling');
INSERT INTO ProductName VALUES ('Foothills');
INSERT INTO ProductName VALUES ('Homestead Brown');
INSERT INTO ProductName VALUES ('Kestrel White');
INSERT INTO ProductName VALUES ('China Doll');
INSERT INTO ProductName VALUES ('Beach House');
INSERT INTO ProductName VALUES ('Mexican Sand');
INSERT INTO ProductName VALUES ('Plantation Brown');
INSERT INTO ProductName VALUES ('Dormer Brown');
INSERT INTO ProductName VALUES ('Meadowlark');
INSERT INTO ProductName VALUES ('Burnished Brandy');
INSERT INTO ProductName VALUES ('Dhurrie Beige');
INSERT INTO ProductName VALUES ('Tree Branch');
INSERT INTO ProductName VALUES ('Maison Blanche');
INSERT INTO ProductName VALUES ('Nantucket Dune');
INSERT INTO ProductName VALUES ('Windsor Greige');
INSERT INTO ProductName VALUES ('Sand Beach');
INSERT INTO ProductName VALUES ('Barcelona Beige');
INSERT INTO ProductName VALUES ('Canvas Tan');
INSERT INTO ProductName VALUES ('Urban Putty');
INSERT INTO ProductName VALUES ('Khaki Shade');
INSERT INTO ProductName VALUES ('Outerbanks');
INSERT INTO ProductName VALUES ('Sandy Ridge');
INSERT INTO ProductName VALUES ('Bittersweet Stem');
INSERT INTO ProductName VALUES ('Irish Cream');
INSERT INTO ProductName VALUES ('Tamarind');
INSERT INTO ProductName VALUES ('Cork Wedge');
INSERT INTO ProductName VALUES ('Artisan Tan');
INSERT INTO ProductName VALUES ('Grecian Ivory');
INSERT INTO ProductName VALUES ('Naturel');
INSERT INTO ProductName VALUES ('Avenue Tan');
INSERT INTO ProductName VALUES ('Fenland');
INSERT INTO ProductName VALUES ('Pier');
INSERT INTO ProductName VALUES ('Prairie Grass');
INSERT INTO ProductName VALUES ('Sandbar');
INSERT INTO ProductName VALUES ('Portico');
INSERT INTO ProductName VALUES ('Studio Taupe');
INSERT INTO ProductName VALUES ('Resort Tan');
INSERT INTO ProductName VALUES ('Greek Villa');
INSERT INTO ProductName VALUES ('Bauhaus Buff');
INSERT INTO ProductName VALUES ('Fragile Beauty');
INSERT INTO ProductName VALUES ('Steamed Milk');
INSERT INTO ProductName VALUES ('Patience');
INSERT INTO ProductName VALUES ('Cr ̈ ̈me');
INSERT INTO ProductName VALUES ('Summer White');
INSERT INTO ProductName VALUES ('Medici Ivory');
INSERT INTO ProductName VALUES ('D ̈¦cor White');
INSERT INTO ProductName VALUES ('Impressive Ivory');
INSERT INTO ProductName VALUES ('Lemon Meringue');
INSERT INTO ProductName VALUES ('Roman Column');
INSERT INTO ProductName VALUES ('Restful White');
INSERT INTO ProductName VALUES ('Polar Bear');
INSERT INTO ProductName VALUES ('Oyster Bar');
INSERT INTO ProductName VALUES ('Westhighland White');
INSERT INTO ProductName VALUES ('Natural Tan');
INSERT INTO ProductName VALUES ('Neutral Ground');
INSERT INTO ProductName VALUES ('Stucco');
INSERT INTO ProductName VALUES ('Egret White');
INSERT INTO ProductName VALUES ('Casa Blanca');
INSERT INTO ProductName VALUES ('Lotus Pod');
INSERT INTO ProductName VALUES ('Eaglet Beige');
INSERT INTO ProductName VALUES ('Echelon Ecru');
INSERT INTO ProductName VALUES ('Chop Sticks');
INSERT INTO ProductName VALUES ('Damsel');
INSERT INTO ProductName VALUES ('Blackberry');
INSERT INTO ProductName VALUES ('Borscht');
INSERT INTO ProductName VALUES ('Alaea');
INSERT INTO ProductName VALUES ('Carnelian');
INSERT INTO ProductName VALUES ('Rosettee');
INSERT INTO ProductName VALUES ('Salute');
INSERT INTO ProductName VALUES ('Wild Current');
INSERT INTO ProductName VALUES ('Red Theatre');
INSERT INTO ProductName VALUES ('Sundried Tomato');
INSERT INTO ProductName VALUES ('Stolen Kiss');
INSERT INTO ProductName VALUES ('Antique Red');
INSERT INTO ProductName VALUES ('Show Stopper');
INSERT INTO ProductName VALUES ('Habanero Chile');
INSERT INTO ProductName VALUES ('Red Obsession');
INSERT INTO ProductName VALUES ('Red Barn');
INSERT INTO ProductName VALUES ('Crabby Apple');
INSERT INTO ProductName VALUES ('Rustic Red');
INSERT INTO ProductName VALUES ('Carriage Door');
INSERT INTO ProductName VALUES ('Sommelier');
INSERT INTO ProductName VALUES ('Only Natural');
INSERT INTO ProductName VALUES ('Trek Tan');
INSERT INTO ProductName VALUES ('Sierra Redwood');
INSERT INTO ProductName VALUES ('Brick Paver');
INSERT INTO ProductName VALUES ('Bolero');
INSERT INTO ProductName VALUES ('Dockside Blue');
INSERT INTO ProductName VALUES ('Indigo Batik');
INSERT INTO ProductName VALUES ('Poolhouse');
INSERT INTO ProductName VALUES ('Smoky Blue');
INSERT INTO ProductName VALUES ('Gale Force');
INSERT INTO ProductName VALUES ('Blue Cruise');
INSERT INTO ProductName VALUES ('Santorini Blue');
INSERT INTO ProductName VALUES ('Adrift');
INSERT INTO ProductName VALUES ('Georgian Revival Blue');
INSERT INTO ProductName VALUES ('Turkish Tile');
INSERT INTO ProductName VALUES ('Tranquil Aqua');
INSERT INTO ProductName VALUES ('Mountain Stream');
INSERT INTO ProductName VALUES ('Aqua-Sphere');
INSERT INTO ProductName VALUES ('St. Bart''s');
INSERT INTO ProductName VALUES ('Sea Serpent');
INSERT INTO ProductName VALUES ('Breezy');
INSERT INTO ProductName VALUES ('Mediterranean');
INSERT INTO ProductName VALUES ('Deep Sea Dive');
INSERT INTO ProductName VALUES ('Labradorite');
INSERT INTO ProductName VALUES ('Seaworthy');
INSERT INTO ProductName VALUES ('Silvermist');
INSERT INTO ProductName VALUES ('Homburg Gray');
INSERT INTO ProductName VALUES ('Cascades');
INSERT INTO ProductName VALUES ('Slate Tile');
INSERT INTO ProductName VALUES ('Mount Etna');
INSERT INTO ProductName VALUES ('Zurich White');
INSERT INTO ProductName VALUES ('White Heron');
INSERT INTO ProductName VALUES ('Windfresh White');
INSERT INTO ProductName VALUES ('Grapy');
INSERT INTO ProductName VALUES ('Raisin');
INSERT INTO ProductName VALUES ('City Loft');
INSERT INTO ProductName VALUES ('Modern Gray');
INSERT INTO ProductName VALUES ('Taupe Tone');
INSERT INTO ProductName VALUES ('Pediment');
INSERT INTO ProductName VALUES ('Palisade');
INSERT INTO ProductName VALUES ('Origami White');
INSERT INTO ProductName VALUES ('Oyster White');
INSERT INTO ProductName VALUES ('Jogging Path');
INSERT INTO ProductName VALUES ('Ethereal Mood');
INSERT INTO ProductName VALUES ('Fawn Brindle');
INSERT INTO ProductName VALUES ('Collonade Gray');
INSERT INTO ProductName VALUES ('Pavestone');
INSERT INTO ProductName VALUES ('Pussywillow');
INSERT INTO ProductName VALUES ('Gateway Gray');
INSERT INTO ProductName VALUES ('Thunder Gray');
INSERT INTO ProductName VALUES ('First Star');
INSERT INTO ProductName VALUES ('Crushed Ice');
INSERT INTO ProductName VALUES ('Big Chill');
INSERT INTO ProductName VALUES ('Silverplate');
INSERT INTO ProductName VALUES ('Ellie Gray');
INSERT INTO ProductName VALUES ('Front Porch');
INSERT INTO ProductName VALUES ('Mineral Deposit');
INSERT INTO ProductName VALUES ('Silverpointe');
INSERT INTO ProductName VALUES ('Lattice');
INSERT INTO ProductName VALUES ('Stamped Concrete');
INSERT INTO ProductName VALUES ('Rhinestone');
INSERT INTO ProductName VALUES ('Tinsmith');
INSERT INTO ProductName VALUES ('Gray Clouds');
INSERT INTO ProductName VALUES ('Gris');
INSERT INTO ProductName VALUES ('Earl Grey');
INSERT INTO ProductName VALUES ('Reflection');
INSERT INTO ProductName VALUES ('Evening Shadow');
INSERT INTO ProductName VALUES ('Monorail Silver');
INSERT INTO ProductName VALUES ('Steely Gray');
INSERT INTO ProductName VALUES ('Wall Street');
INSERT INTO ProductName VALUES ('Fleur De Sel');
INSERT INTO ProductName VALUES ('Zircon');
INSERT INTO ProductName VALUES ('March Wind');
INSERT INTO ProductName VALUES ('Summit Gray');
INSERT INTO ProductName VALUES ('Gray Shingle');
INSERT INTO ProductName VALUES ('On The Rocks');
INSERT INTO ProductName VALUES ('Knitting Needles');
INSERT INTO ProductName VALUES ('Pewter Cast');
INSERT INTO ProductName VALUES ('Peppercorn');
INSERT INTO ProductName VALUES ('Sealskin');
INSERT INTO ProductName VALUES ('Paper Lantern');
INSERT INTO ProductName VALUES ('Gold Vessel');
INSERT INTO ProductName VALUES ('Cottage Cream');
INSERT INTO ProductName VALUES ('Golden Gate');
INSERT INTO ProductName VALUES ('Lanyard');
INSERT INTO ProductName VALUES ('Tea Light');
INSERT INTO ProductName VALUES ('Bee''s Wax');
INSERT INTO ProductName VALUES ('Buff');
INSERT INTO ProductName VALUES ('Concord Buff');
INSERT INTO ProductName VALUES ('White Raisin');
INSERT INTO ProductName VALUES ('Hinoki');
INSERT INTO ProductName VALUES ('August Moon');
INSERT INTO ProductName VALUES ('Sundew');
INSERT INTO ProductName VALUES ('Row House Tan');
INSERT INTO ProductName VALUES ('Townhall Tan');
INSERT INTO ProductName VALUES ('Biltmore Buff');
INSERT INTO ProductName VALUES ('Cupola Yellow');
INSERT INTO ProductName VALUES ('Stonebriar');
INSERT INTO ProductName VALUES ('Dromedary Camel');
INSERT INTO ProductName VALUES ('Mesa Tan');
INSERT INTO ProductName VALUES ('Toasted Pine Nut');
INSERT INTO ProductName VALUES ('Safari');
INSERT INTO ProductName VALUES ('Straw Harvest');
INSERT INTO ProductName VALUES ('Rustic City');
INSERT INTO ProductName VALUES ('Olde World Gold');
INSERT INTO ProductName VALUES ('Cavern Clay');
INSERT INTO ProductName VALUES ('Spiced Cider');
INSERT INTO ProductName VALUES ('Earthen Jug');
INSERT INTO ProductName VALUES ('Tower Tan');
INSERT INTO ProductName VALUES ('Wheat Penny');
INSERT INTO ProductName VALUES ('Creole Cottage');
INSERT INTO ProductName VALUES ('Copper Wire');
INSERT INTO ProductName VALUES ('Rustic Adobe');
INSERT INTO ProductName VALUES ('Copper Pot');
INSERT INTO ProductName VALUES ('Brandywine');
INSERT INTO ProductName VALUES ('Pueblo');
INSERT INTO ProductName VALUES ('Townhouse Tan');
INSERT INTO ProductName VALUES ('Tawny Tan');
INSERT INTO ProductName VALUES ('Oak Barrel');
INSERT INTO ProductName VALUES ('Pottery Urn');
INSERT INTO ProductName VALUES ('Croissant');
INSERT INTO ProductName VALUES ('Ligonier Tan');
INSERT INTO ProductName VALUES ('Oak Creek');
INSERT INTO ProductName VALUES ('Fresco Cream');
INSERT INTO ProductName VALUES ('Deer Valley');
INSERT INTO ProductName VALUES ('Crescent Cream');
INSERT INTO ProductName VALUES ('Travertine');
INSERT INTO ProductName VALUES ('Colony Buff');
INSERT INTO ProductName VALUES ('Canoe');
INSERT INTO ProductName VALUES ('Yearling');
INSERT INTO ProductName VALUES ('Lemon Verbena');
INSERT INTO ProductName VALUES ('Koi Pond');
INSERT INTO ProductName VALUES ('Green Sprout');
INSERT INTO ProductName VALUES ('Edamame');
INSERT INTO ProductName VALUES ('Forestwood');
INSERT INTO ProductName VALUES ('San Antonio Sage');
INSERT INTO ProductName VALUES ('Lemongrass');
INSERT INTO ProductName VALUES ('Bamboo Shoot');
INSERT INTO ProductName VALUES ('Olive Grove');
INSERT INTO ProductName VALUES ('Palm Leaf');
INSERT INTO ProductName VALUES ('Garden Sage');
INSERT INTO ProductName VALUES ('Meadow Trail');
INSERT INTO ProductName VALUES ('Cargo Pants');
INSERT INTO ProductName VALUES ('Herbal Wash');
INSERT INTO ProductName VALUES ('Messenger Bag');
INSERT INTO ProductName VALUES ('Willow Tree');
INSERT INTO ProductName VALUES ('Agate Green');
INSERT INTO ProductName VALUES ('Mountain Road');
INSERT INTO ProductName VALUES ('Zeus');
INSERT INTO ProductName VALUES ('Muddled Basil');
INSERT INTO ProductName VALUES ('Rushing River');
INSERT INTO ProductName VALUES ('Recycled Glass');
INSERT INTO ProductName VALUES ('Green Earth');
INSERT INTO ProductName VALUES ('Laurel Woods');
